import React, { createContext, useContext, useState, useEffect } from "react";

export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  dir?: "ltr" | "rtl";
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", dir: "ltr" },
  { code: "hi", name: "Hindi", nativeName: "हिंदी", dir: "ltr" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", dir: "ltr" },
  { code: "ar", name: "Arabic", nativeName: "العربية", dir: "rtl" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", dir: "ltr" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", dir: "ltr" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", dir: "ltr" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", dir: "ltr" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", dir: "ltr" },
];

export type TranslationKey =
  | "app_name"
  | "app_tagline"
  | "system_live"
  | "processing_audio"
  | "light"
  | "dark"
  | "lang_label"
  | "history"
  | "logged_in_as"
  | "sign_out"
  | "critical_threat"
  | "elevated_threat"
  | "moderate_risk"
  | "low_risk"
  | "very_low_risk"
  | "alert_high_risk_call"
  | "alert_safe_call"
  | "alert_cautious_call"
  | "rerun_analysis"
  | "analysis_time"
  | "source"
  | "file"
  | "sample"
  | "microphone"
  | "upload"
  | "temporal_window_slices"
  | "window_resolution"
  | "live_microphone"
  | "upload_audio_file"
  | "time_window"
  | "mic_ready"
  | "live_audio_capture"
  | "mic_ready_desc"
  | "mic_recording_desc"
  | "live_pitch"
  | "live_energy"
  | "duration"
  | "noise_reduction"
  | "rms_normalization"
  | "on"
  | "off"
  | "live_speech_stream"
  | "listening_words"
  | "drop_audio_here"
  | "browse"
  | "supports_formats"
  | "benchmark_scenarios"
  | "decoded_ready"
  | "loading_benchmark"
  | "error_benchmark"
  | "live_acoustic_graph"
  | "streaming_active"
  | "oscilloscope_ready"
  | "hybrid"
  | "oscilloscope"
  | "fft_spectrum"
  | "signal"
  | "standby"
  | "interaction_risk_gauge"
  | "risk_index"
  | "badge_very_low"
  | "badge_low"
  | "badge_moderate"
  | "badge_elevated"
  | "badge_high"
  | "status_very_low"
  | "status_low"
  | "status_moderate"
  | "status_elevated"
  | "status_high"
  | "natural_patterns"
  | "elevated_urgency"
  | "high_confidence_deepfake"
  | "synthetic_probability"
  | "risk_weights_breakdown"
  | "hide"
  | "vectors_count"
  | "vector1_title"
  | "vector1_desc"
  | "vector2_title"
  | "vector2_desc"
  | "vector3_title"
  | "vector3_desc"
  | "vector4_title"
  | "vector4_desc"
  | "composite_formula"
  | "weight_40"
  | "weight_25"
  | "weight_10"
  | "speech_to_text_title"
  | "speech_to_text_subtitle"
  | "side_by_side"
  | "original"
  | "translation"
  | "original_transcript_title"
  | "live_translation_title"
  | "awaiting_audio"
  | "translating_realtime"
  | "translation_will_appear"
  | "copy_original"
  | "copy_translation"
  | "copied"
  | "tone_telemetry_title"
  | "tone_telemetry_subtitle"
  | "acoustic_ml_badge"
  | "pitch_f0"
  | "range"
  | "jitter"
  | "elevated"
  | "stable"
  | "energy_level"
  | "rms_headroom"
  | "tone_classification"
  | "inferred_vocal_stance"
  | "neural_formant_analysis"
  | "prosody_rate"
  | "speech_flow_cadence"
  | "naturalness"
  | "pause_duration"
  | "avg_intersyllabic_gap"
  | "unusually_rapid_synthetic"
  | "natural_breathing_gap"
  | "pause_frequency"
  | "breathing_rate"
  | "centroid"
  | "suspicious_vocab_title"
  | "suspicious_vocab_subtitle"
  | "detected"
  | "all"
  | "category"
  | "no_suspicious_markers"
  | "critical"
  | "high"
  | "medium"
  | "risk_timeline_title"
  | "risk_timeline_subtitle"
  | "all_metrics"
  | "composite"
  | "voice_clone"
  | "vocabulary"
  | "tone_prosody"
  | "peak_voice"
  | "peak_vocab"
  | "windows_analyzed"
  | "slice_resolution"
  | "intervals"
  | "no_timeline_data"
  | "ai_summary_title"
  | "ai_summary_subtitle"
  | "awaiting_analysis_pass"
  | "copy"
  | "export_json"
  | "save_to_history"
  | "saved_to_vault"
  | "delete_audio_reset"
  | "vault_history_title"
  | "vault_history_subtitle"
  | "search_history_placeholder"
  | "export_csv"
  | "clear_all"
  | "load"
  | "delete_record"
  | "no_audit_logs"
  | "duration_suffix"
  | "login_id_label"
  | "login_id_placeholder"
  | "security_password_label"
  | "default_label"
  | "demo_credentials_title"
  | "auto_fill"
  | "remember_session"
  | "auth_error_title"
  | "enter_credentials_error"
  | "invalid_credentials_error"
  | "signing_in"
  | "sign_in_btn"
  | "security_protocol_notice"
  | "pipeline_running"
  | "processing_frames"
  | "voice_authenticity_risk"
  | "neural_clone_detected"
  | "natural_bio_voice"
  | "flagged_threat_words"
  | "phrases"
  | "urgency_phishing"
  | "clean_vocabulary"
  | "interaction_stability"
  | "stability_index"
  | "saved_audit_sessions"
  | "search_placeholder"
  | "risk"
  | "threat_words"
  | "time"
  | string;

// Note: As explicitly requested, the name of the app "Hertzy" is NOT translated and remains "Hertzy" in all languages.
const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    app_name: "Hertzy",
    app_tagline: "Every voice has a Signature",
    system_live: "System Live",
    processing_audio: "Processing Audio",
    light: "Light",
    dark: "Dark",
    lang_label: "Lang:",
    history: "History",
    logged_in_as: "Logged in as",
    sign_out: "Sign out",
    critical_threat: "Critical Threat",
    elevated_threat: "Elevated Threat",
    moderate_risk: "Moderate Risk",
    low_risk: "Low Risk",
    very_low_risk: "Very Low Risk",
    alert_high_risk_call: "Security Alert: High Risk Voice Call Detected — Possible Deepfake Voice Clone Scam",
    alert_safe_call: "Security Notice: Verified Safe Call — Authentic Human Voice Signature",
    alert_cautious_call: "Security Notice: Cautious Call — Acoustic or Vocabulary Anomalies Detected",
    rerun_analysis: "Re-run Analysis",
    analysis_time: "Analysis Time",
    source: "Source",
    file: "File",
    sample: "Sample",
    microphone: "Microphone",
    upload: "Upload",
    temporal_window_slices: "Temporal Window Slices:",
    window_resolution: "Window Resolution:",
    live_microphone: "Live Microphone",
    upload_audio_file: "Upload Audio File",
    time_window: "Time Window:",
    mic_ready: "Microphone Ready",
    live_audio_capture: "Live Audio Capture in Progress",
    mic_ready_desc: "Click microphone to record live speech. Real-time words and acoustic telemetry will display below.",
    mic_recording_desc: "Streaming acoustic samples to Hertzy Real-time Classifier. Speak naturally or test phishing phrases.",
    live_pitch: "Live Pitch",
    live_energy: "Live Energy",
    duration: "Duration",
    noise_reduction: "Noise Reduction",
    rms_normalization: "RMS Normalization",
    on: "ON",
    off: "OFF",
    live_speech_stream: "Live Real-time Speech Stream:",
    listening_words: "Listening for spoken words...",
    drop_audio_here: "Drop recorded audio file here or",
    browse: "browse",
    supports_formats: "Supports .wav, .mp3, .m4a, .ogg up to 50MB",
    benchmark_scenarios: "Benchmark Audio Scenarios (Click to test):",
    decoded_ready: "Decoded & Ready",
    loading_benchmark: "Loading benchmark scenario:",
    error_benchmark: "Error generating benchmark acoustic signal.",
    live_acoustic_graph: "Live Acoustic Graph",
    streaming_active: "Streaming Active",
    oscilloscope_ready: "Real-time Oscilloscope Ready",
    hybrid: "Hybrid",
    oscilloscope: "Oscilloscope",
    fft_spectrum: "FFT Spectrum",
    signal: "Signal",
    standby: "Standby",
    interaction_risk_gauge: "Interaction Risk Gauge",
    risk_index: "Risk Index",
    badge_very_low: "0-20 Very Low",
    badge_low: "21-40 Low",
    badge_moderate: "41-60 Moderate",
    badge_elevated: "61-80 Elevated",
    badge_high: "81-100 High",
    status_very_low: "Very Low Risk (Secure)",
    status_low: "Low Risk (Normal)",
    status_moderate: "Moderate Risk (Caution)",
    status_elevated: "Elevated Threat (Anomalous)",
    status_high: "High Threat (Deepfake Scam)",
    natural_patterns: "Acoustic & vocab patterns natural",
    elevated_urgency: "Elevated urgency / vocal strain",
    high_confidence_deepfake: "High confidence deepfake impersonation",
    synthetic_probability: "Hertzy Synthetic Probability:",
    risk_weights_breakdown: "Risk Assessment Weights Breakdown",
    hide: "Hide",
    vectors_count: "4 Vectors (100%)",
    vector1_title: "1. Voice Authenticity & Deepfake Telemetry",
    vector1_desc: "Spectral phase slips, formant harmonics, vocoder artifacts, F0 jitter.",
    vector2_title: "2. Vocabulary, Phishing & Extortion Keywords",
    vector2_desc: "OTP harvesting, false authority impersonation, bank transfer demands.",
    vector3_title: "3. Tone, Prosody & Acoustic Stress",
    vector3_desc: "Speech tempo (WPM), intersyllabic pause cadence, unnatural monotone.",
    vector4_title: "4. Contextual Urgency & Channel Isolation",
    vector4_desc: "Artificial deadlines ('within 15m'), 'do not call my cell', bypass rules.",
    composite_formula: "Composite Score Formula:",
    weight_40: "40% Weight",
    weight_25: "25% Weight",
    weight_10: "10% Weight",
    speech_to_text_title: "Live Speech-to-Text & Translation",
    speech_to_text_subtitle: "Synchronized Multi-Modal Linguistic Engine",
    side_by_side: "Side-by-Side",
    original: "Original",
    translation: "Translation",
    original_transcript_title: "Original Audio Transcript (with Flagged Phrases)",
    live_translation_title: "Live Translation",
    awaiting_audio: "Awaiting audio feed for live transcription...",
    translating_realtime: "Translating in real-time...",
    translation_will_appear: "Translation will appear here dynamically as speech is processed...",
    copy_original: "Copy Original",
    copy_translation: "Copy Translation",
    copied: "Copied!",
    tone_telemetry_title: "Tone & Acoustic Prosody Telemetry",
    tone_telemetry_subtitle: "F0 Pitch, Energy RMS, Rhythm & Pause Dispersion",
    acoustic_ml_badge: "Hertzy Acoustic ML",
    pitch_f0: "Pitch (F0)",
    range: "Range:",
    jitter: "Jitter:",
    elevated: "Elevated",
    stable: "Stable",
    energy_level: "Energy Level",
    rms_headroom: "RMS Dynamic Headroom",
    tone_classification: "Tone Classification",
    inferred_vocal_stance: "Inferred Vocal Stance",
    neural_formant_analysis: "Neural Formant Analysis",
    prosody_rate: "Prosody Rate",
    speech_flow_cadence: "Speech Flow Cadence",
    naturalness: "Naturalness:",
    pause_duration: "Pause Duration",
    avg_intersyllabic_gap: "Avg Intersyllabic Gap",
    unusually_rapid_synthetic: "⚠️ Unusually Rapid/Synthetic",
    natural_breathing_gap: "✓ Natural Breathing Gap",
    pause_frequency: "Pause Frequency",
    breathing_rate: "Breathing & Hesitation Rate",
    centroid: "Centroid:",
    suspicious_vocab_title: "Suspicious Vocabulary & Threat Phrases",
    suspicious_vocab_subtitle: "Semantic Coercion & Financial Phishing Filter",
    detected: "Detected",
    all: "All",
    category: "Category:",
    no_suspicious_markers: "No suspicious vocabulary markers detected.",
    critical: "CRITICAL",
    high: "HIGH",
    medium: "MEDIUM",
    risk_timeline_title: "Risk vs. Time Graph",
    risk_timeline_subtitle: "Temporal Window Analysis",
    all_metrics: "All Metrics",
    composite: "Composite",
    voice_clone: "Voice Clone",
    vocabulary: "Vocabulary",
    tone_prosody: "Tone / Prosody",
    peak_voice: "Peak Voice:",
    peak_vocab: "Peak Vocab:",
    windows_analyzed: "Windows Analyzed:",
    slice_resolution: "Slice Resolution:",
    intervals: "intervals",
    no_timeline_data: "No timeline data. Upload audio or record microphone to generate temporal risk profile.",
    ai_summary_title: "AI Executive Risk Summary",
    ai_summary_subtitle: "Synthesized Multi-Modal Threat Assessment (4-5 Point Analysis)",
    awaiting_analysis_pass: "AI Risk Synthesis awaiting completed audio analysis pass.",
    copy: "Copy",
    export_json: "Export JSON",
    save_to_history: "Save to Vault History",
    saved_to_vault: "Saved to Vault",
    delete_audio_reset: "Delete Audio / Reset",
    vault_history_title: "Audio Analysis Vault History",
    vault_history_subtitle: "saved audit sessions & acoustic telemetry records",
    search_history_placeholder: "Search audit sessions by title, transcript keyword...",
    export_csv: "Export CSV",
    clear_all: "Clear All",
    load: "Load",
    delete_record: "Delete record",
    no_audit_logs: "No audit logs found. Save an analyzed session to view records here.",
    duration_suffix: "duration",
    login_id_label: "Login ID / User Identifier",
    login_id_placeholder: "Enter 'demo' or user ID",
    security_password_label: "Security Password",
    default_label: "Default:",
    demo_credentials_title: "Demo Credentials:",
    auto_fill: "Auto-fill",
    remember_session: "Remember session on this device",
    auth_error_title: "Authentication Error",
    enter_credentials_error: "Please enter your Login ID and Password to authenticate.",
    invalid_credentials_error: "Invalid credentials. Use 'demo' and 'demo123'.",
    signing_in: "Authenticating...",
    sign_in_btn: "Authenticate & Access Vault",
    security_protocol_notice: "Secured with end-to-end cryptographic integrity, voice biometric protection, and isolated multi-tenant audit logs.",
  },
  hi: {
    app_name: "Hertzy",
    app_tagline: "हर आवाज़ का एक सिग्नेचर होता है",
    system_live: "सिस्टम लाइव",
    processing_audio: "ऑडियो प्रोसेसिंग जारी",
    light: "लाइट",
    dark: "डार्क",
    lang_label: "भाषा:",
    history: "इतिहास",
    logged_in_as: "लॉग इन:",
    sign_out: "साइन आउट",
    critical_threat: "गंभीर ख़तरा",
    elevated_threat: "बढ़ा हुआ ख़तरा",
    moderate_risk: "मध्यम जोखिम",
    low_risk: "कम जोखिम",
    very_low_risk: "अत्यंत कम जोखिम",
    alert_high_risk_call: "सुरक्षा चेतावनी: उच्च जोखिम वाली वॉयस कॉल मिली — संभावित डीपफेक वॉयस क्लोन स्कैम",
    alert_safe_call: "सुरक्षा सूचना: सुरक्षित कॉल सत्यापित — प्रामाणिक मानव ध्वनि हस्ताक्षर",
    alert_cautious_call: "सुरक्षा सूचना: सतर्क कॉल — ध्वनिक या शब्दावली विसंगतियाँ पाई गईं",
    rerun_analysis: "पुनः विश्लेषण चलाएं",
    analysis_time: "विश्लेषण समय",
    source: "स्रोत",
    file: "फ़ाइल",
    sample: "नमूना",
    microphone: "माइक्रोफ़ोन",
    upload: "अपलोड",
    temporal_window_slices: "कालिक विंडो स्लाइस:",
    window_resolution: "विंडो रिज़ॉल्यूशन:",
    live_microphone: "लाइव माइक्रोफ़ोन",
    upload_audio_file: "ऑडियो फ़ाइल अपलोड करें",
    time_window: "समय विंडो:",
    mic_ready: "माइक्रोफ़ोन तैयार है",
    live_audio_capture: "लाइव ऑडियो कैप्चर जारी है",
    mic_ready_desc: "लाइव भाषण रिकॉर्ड करने के लिए माइक्रोफ़ोन पर क्लिक करें। रीयल-टाइम शब्द और ध्वनिक टेलीमेट्री नीचे दिखाई देंगे।",
    mic_recording_desc: "Hertzy रीयल-टाइम क्लासिफायर को ध्वनिक नमूने भेजे जा रहे हैं। स्वाभाविक रूप से बोलें या फ़िशिंग वाक्यांशों का परीक्षण करें।",
    live_pitch: "लाइव पिच",
    live_energy: "लाइव ऊर्जा",
    duration: "अवधि",
    noise_reduction: "शोर में कमी",
    rms_normalization: "RMS सामान्यीकरण",
    on: "चालू",
    off: "बंद",
    live_speech_stream: "लाइव रीयल-टाइम भाषण स्ट्रीम:",
    listening_words: "बोले गए शब्दों की प्रतीक्षा...",
    drop_audio_here: "रिकॉर्ड की गई ऑडियो फ़ाइल यहाँ छोड़ें या",
    browse: "ब्राउज़ करें",
    supports_formats: ".wav, .mp3, .m4a, .ogg (अधिकतम 50MB तक समर्थित)",
    benchmark_scenarios: "बेंचमार्क ऑडियो परिदृश्य (परीक्षण के लिए क्लिक करें):",
    decoded_ready: "डिकोड व तैयार",
    loading_benchmark: "बेंचमार्क परिदृश्य लोड हो रहा है:",
    error_benchmark: "बेंचमार्क ध्वनिक संकेत उत्पन्न करने में त्रुटि।",
    live_acoustic_graph: "लाइव ध्वनिक ग्राफ़",
    streaming_active: "स्ट्रीमिंग सक्रिय",
    oscilloscope_ready: "रीयल-टाइम ऑसिलोस्कोप तैयार",
    hybrid: "हाइब्रिड",
    oscilloscope: "ऑसिलोस्कोप",
    fft_spectrum: "FFT स्पेक्ट्रम",
    signal: "सिग्नल",
    standby: "स्टैंडबाय",
    interaction_risk_gauge: "इंटरैक्शन जोखिम गेज",
    risk_index: "जोखिम सूचकांक",
    badge_very_low: "0-20 अत्यंत कम",
    badge_low: "21-40 कम",
    badge_moderate: "41-60 मध्यम",
    badge_elevated: "61-80 बढ़ा हुआ",
    badge_high: "81-100 उच्च",
    status_very_low: "अत्यंत कम जोखिम (सुरक्षित)",
    status_low: "कम जोखिम (सामान्य)",
    status_moderate: "मध्यम जोखिम (सावधानी)",
    status_elevated: "बढ़ा हुआ ख़तरा (विसंगत)",
    status_high: "उच्च ख़तरा (डीपफेक स्कैम)",
    natural_patterns: "ध्वनिक और शब्दावली पैटर्न स्वाभाविक हैं",
    elevated_urgency: "बढ़ी हुई तात्कालिकता / स्वर का तनाव",
    high_confidence_deepfake: "उच्च विश्वास डीपफेक प्रतिरूपण",
    synthetic_probability: "Hertzy सिंथेटिक संभावना:",
    risk_weights_breakdown: "जोखिम मूल्यांकन भार विभाजन",
    hide: "छिपाएं",
    vectors_count: "4 वैक्टर (100%)",
    vector1_title: "1. स्वर प्रामाणिकता और डीपफेक टेलीमेट्री",
    vector1_desc: "स्पेक्ट्रल फेज़ स्लिप्स, फॉर्मैंट हार्मोनिक्स, वोकोडर कलाकृतियां, F0 जिटर।",
    vector2_title: "2. शब्दावली, फ़िशिंग और जबरन वसूली कीवर्ड",
    vector2_desc: "ओटीपी संकलन, झूठे प्राधिकारी प्रतिरूपण, बैंक ट्रांसफर मांग।",
    vector3_title: "3. टोन, प्रोसोडी और ध्वनिक तनाव",
    vector3_desc: "भाषण गति (WPM), अक्षरों के बीच विराम लय, अस्वाभाविक एकरसता।",
    vector4_title: "4. प्रासंगिक तात्कालिकता और चैनल अलगाव",
    vector4_desc: "कृत्रिम समय सीमा ('15 मिनट के भीतर'), 'मेरे सेल पर कॉल न करें', नियम बाईपास।",
    composite_formula: "समग्र स्कोर सूत्र:",
    weight_40: "40% भार",
    weight_25: "25% भार",
    weight_10: "10% भार",
    speech_to_text_title: "लाइव वाक्-से-पाठ और अनुवाद",
    speech_to_text_subtitle: "सिंक्रनाइज़्ड मल्टी-मॉडल भाषाई इंजन",
    side_by_side: "साथ-साथ",
    original: "मूल",
    translation: "अनुवाद",
    original_transcript_title: "मूल ऑडियो प्रतिलेख (फ़्लैग किए गए वाक्यांशों के साथ)",
    live_translation_title: "लाइव अनुवाद",
    awaiting_audio: "लाइव प्रतिलेखन के लिए ऑडियो फ़ीड की प्रतीक्षा...",
    translating_realtime: "रीयल-टाइम में अनुवाद हो रहा है...",
    translation_will_appear: "भाषण संसाधित होते ही अनुवाद यहाँ गतिशील रूप से दिखाई देगा...",
    copy_original: "मूल कॉपी करें",
    copy_translation: "अनुवाद कॉपी करें",
    copied: "कॉपी हो गया!",
    tone_telemetry_title: "टोन और ध्वनिक प्रोसोडी टेलीमेट्री",
    tone_telemetry_subtitle: "F0 पिच, ऊर्जा RMS, लय और ठहराव फैलाव",
    acoustic_ml_badge: "Hertzy एकॉस्टिक ML",
    pitch_f0: "पिच (F0)",
    range: "रेंज:",
    jitter: "जिटर:",
    elevated: "बढ़ा हुआ",
    stable: "स्थिर",
    energy_level: "ऊर्जा स्तर",
    rms_headroom: "RMS डायनामिक हेडरूम",
    tone_classification: "टोन वर्गीकरण",
    inferred_vocal_stance: "अनुमानित स्वर मुद्रा",
    neural_formant_analysis: "न्यूरल फॉर्मैंट विश्लेषण",
    prosody_rate: "प्रोसोडी दर",
    speech_flow_cadence: "भाषण प्रवाह लय",
    naturalness: "स्वाभाविकता:",
    pause_duration: "विराम अवधि",
    avg_intersyllabic_gap: "औसत शब्दांश अंतराल",
    unusually_rapid_synthetic: "⚠️ असामान्य रूप से तेज़/सिंथेटिक",
    natural_breathing_gap: "✓ प्राकृतिक सांस लेने का अंतराल",
    pause_frequency: "विराम आवृत्ति",
    breathing_rate: "सांस और झिझक दर",
    centroid: "सेंट्रोइड:",
    suspicious_vocab_title: "संदिग्ध शब्दावली और ख़तरे के वाक्यांश",
    suspicious_vocab_subtitle: "सिमेंटिक दबाव और वित्तीय फ़िशिंग फ़िल्टर",
    detected: "मिले",
    all: "सभी",
    category: "श्रेणी:",
    no_suspicious_markers: "कोई संदिग्ध शब्दावली मार्कर नहीं मिले।",
    critical: "गंभीर",
    high: "उच्च",
    medium: "मध्यम",
    risk_timeline_title: "जोखिम बनाम समय ग्राफ़",
    risk_timeline_subtitle: "कालिक विंडो विश्लेषण",
    all_metrics: "सभी मेट्रिक्स",
    composite: "समग्र",
    voice_clone: "वॉयस क्लोन",
    vocabulary: "शब्दावली",
    tone_prosody: "टोन / प्रोसोडी",
    peak_voice: "शीर्ष वॉयस:",
    peak_vocab: "शीर्ष शब्दावली:",
    windows_analyzed: "विश्लेषण की गई विंडो:",
    slice_resolution: "स्लाइस रिज़ॉल्यूशन:",
    intervals: "अंतराल",
    no_timeline_data: "कोई समयरेखा डेटा नहीं। ऑडियो अपलोड करें या माइक से रिकॉर्ड करें।",
    ai_summary_title: "AI कार्यकारी जोखिम सारांश",
    ai_summary_subtitle: "संश्लेषित बहु-मॉडल ख़तरा मूल्यांकन (4-5 बिंदु विश्लेषण)",
    awaiting_analysis_pass: "AI जोखिम संश्लेषण पूर्ण ऑडियो विश्लेषण की प्रतीक्षा कर रहा है।",
    copy: "कॉपी करें",
    export_json: "JSON निर्यात करें",
    save_to_history: "वॉल्ट इतिहास में सहेजें",
    saved_to_vault: "वॉल्ट में सुरक्षित",
    delete_audio_reset: "ऑडियो हटाएं / रीसेट करें",
    vault_history_title: "ऑडियो विश्लेषण वॉल्ट इतिहास",
    vault_history_subtitle: "सहेजे गए ऑडिट सत्र और ध्वनिक रिकॉर्ड",
    search_history_placeholder: "शीर्षक या कीवर्ड द्वारा ऑडिट सत्र खोजें...",
    export_csv: "CSV निर्यात करें",
    clear_all: "सभी साफ़ करें",
    load: "लोड करें",
    delete_record: "रिकॉर्ड हटाएं",
    no_audit_logs: "कोई ऑडिट लॉग नहीं मिला। रिकॉर्ड देखने के लिए सत्र सहेजें।",
    duration_suffix: "अवधि",
    login_id_label: "लॉगिन आईडी / उपयोगकर्ता पहचानकर्ता",
    login_id_placeholder: "'demo' या यूजर आईडी दर्ज करें",
    security_password_label: "सुरक्षा पासवर्ड",
    default_label: "डिफ़ॉल्ट:",
    demo_credentials_title: "डेमो क्रेडेंशियल:",
    auto_fill: "स्वतः भरें",
    remember_session: "इस डिवाइस पर सत्र याद रखें",
    auth_error_title: "प्रमाणीकरण त्रुटि",
    enter_credentials_error: "प्रमाणीकृत करने के लिए कृपया अपनी लॉगिन आईडी और पासवर्ड दर्ज करें।",
    invalid_credentials_error: "अमान्य क्रेडेंशियल। 'demo' और 'demo123' का उपयोग करें।",
    signing_in: "प्रमाणीकरण जारी...",
    sign_in_btn: "प्रमाणीकृत करें और वॉल्ट खोलें",
    security_protocol_notice: "एंड-टू-एंड क्रिप्टोग्राफ़िक अखंडता और वॉयस बायोमेट्रिक सुरक्षा द्वारा सुरक्षित।",
  },
  te: {
    app_name: "Hertzy",
    app_tagline: "ప్రతి స్వరం ఒక సంతకం కలిగి ఉంటుంది",
    system_live: "సిస్టమ్ లైవ్",
    processing_audio: "ఆడియో ప్రాసెసింగ్",
    light: "లైట్",
    dark: "డార్క్",
    lang_label: "భాష:",
    history: "చరిత్ర",
    logged_in_as: "లాగిన్ అయ్యారు:",
    sign_out: "సైన్ అవుట్",
    critical_threat: "తీవ్రమైన ముప్పు",
    elevated_threat: "ఎలివేటెడ్ ముప్పు",
    moderate_risk: "మితమైన ప్రమాదం",
    low_risk: "తక్కువ ప్రమాదం",
    very_low_risk: "చాలా తక్కువ ప్రమాదం",
    alert_high_risk_call: "భద్రతా హెచ్చరిక: అధిక ప్రమాద వాయిస్ కాల్ గుర్తించబడింది — సంభావ్య డీప్‌ఫేక్ వాయిస్ క్లోన్ మోసం",
    alert_safe_call: "భద్రతా నోటీసు: ధృవీకరించబడిన సురక్షిత కాల్ — నిజమైన మానవ స్వరం",
    alert_cautious_call: "భద్రతా నోటీసు: జాగ్రత్త వహించాల్సిన కాల్ — ధ్వని లేదా పదజాల అసమానతలు గుర్తించబడ్డాయి",
    rerun_analysis: "మళ్ళీ విశ్లేషించండి",
    analysis_time: "విశ్లేషణ సమయం",
    source: "మూలం",
    file: "ఫైల్",
    sample: "నమూనా",
    microphone: "మైక్రోఫోన్",
    upload: "అప్‌లోడ్",
    temporal_window_slices: "సమయ విండో భాగాలు:",
    window_resolution: "విండో రిజల్యూషన్:",
    live_microphone: "లైవ్ మైక్రోఫోన్",
    upload_audio_file: "ఆడియో ఫైల్‌ను అప్‌లోడ్ చేయండి",
    time_window: "సమయ విండో:",
    mic_ready: "మైక్రోఫోన్ సిద్ధంగా ఉంది",
    live_audio_capture: "లైవ్ ఆడియో క్యాప్చర్ పురోగతిలో ఉంది",
    mic_ready_desc: "లైవ్ ప్రసంగాన్ని రికార్డ్ చేయడానికి మైక్రోఫోన్ క్లిక్ చేయండి. నిజ-సమయ పదాలు మరియు ధ్వని టెలిమెట్రీ కింద కనిపిస్తాయి.",
    mic_recording_desc: "Hertzy రియల్-టైమ్ క్లాసిఫైయర్‌కు ధ్వని నమూనాలు స్ట్రీమ్ చేయబడుతున్నాయి. సహజంగా మాట్లాడండి.",
    live_pitch: "లైవ్ పిచ్",
    live_energy: "లైవ్ ఎనర్జీ",
    duration: "వ్యవధి",
    noise_reduction: "శబ్ద తగ్గింపు",
    rms_normalization: "RMS సాధారణీకరణ",
    on: "ఆన్",
    off: "ఆఫ్",
    live_speech_stream: "లైవ్ రియల్-టైమ్ స్పీచ్ స్ట్రీమ్:",
    listening_words: "మాట్లాడే పదాల కోసం వింటున్నది...",
    drop_audio_here: "రికార్డ్ చేసిన ఆడియో ఫైల్‌ను ఇక్కడ డ్రాప్ చేయండి లేదా",
    browse: "బ్రౌజ్ చేయండి",
    supports_formats: ".wav, .mp3, .m4a, .ogg (గరిష్టంగా 50MB వరకు మద్దతు)",
    benchmark_scenarios: "బెంచ్‌మార్క్ ఆడియో దృశ్యాలు (పరీక్షించడానికి క్లిక్ చేయండి):",
    decoded_ready: "డీకోడ్ చేయబడింది & సిద్ధంగా ఉంది",
    loading_benchmark: "బెంచ్‌మార్క్ దృశ్యం లోడ్ అవుతోంది:",
    error_benchmark: "బెంచ్‌మార్క్ ధ్వని సిగ్నల్‌ను రూపొందించడంలో లోపం.",
    live_acoustic_graph: "లైవ్ అకౌస్టిక్ గ్రాఫ్",
    streaming_active: "స్ట్రీమింగ్ సక్రియంగా ఉంది",
    oscilloscope_ready: "రియల్-టైమ్ ఒసిల్లోస్కోప్ సిద్ధం",
    hybrid: "హైబ్రిడ్",
    oscilloscope: "ఒసిల్లోస్కోప్",
    fft_spectrum: "FFT స్పెక్ట్రమ్",
    signal: "సిగ్నల్",
    standby: "స్టాండ్‌బై",
    interaction_risk_gauge: "ఇంటరాక్షన్ రిస్క్ గేజ్",
    risk_index: "రిస్క్ ఇండెక్స్",
    badge_very_low: "0-20 చాలా తక్కువ",
    badge_low: "21-40 తక్కువ",
    badge_moderate: "41-60 మితమైనది",
    badge_elevated: "61-80 ఎలివేటెడ్",
    badge_high: "81-100 అధికం",
    status_very_low: "చాలా తక్కువ ప్రమాదం (సురక్షితం)",
    status_low: "తక్కువ ప్రమాదం (సాధారణం)",
    status_moderate: "మితమైన ప్రమాదం (జాగ్రత్త)",
    status_elevated: "ఎలివేటెడ్ ముప్పు (అసాధారణం)",
    status_high: "అధిక ముప్పు (డీప్‌ఫేక్ స్కామ్)",
    natural_patterns: "ధ్వని & పదజాల నమూనాలు సహజమైనవి",
    elevated_urgency: "ఎలివేటెడ్ అత్యవసరం / వాయిస్ ఒత్తిడి",
    high_confidence_deepfake: "అధిక విశ్వాసంతో డీప్‌ఫేక్ అనుకరణ",
    synthetic_probability: "Hertzy సింథటిక్ సంభావ్యత:",
    risk_weights_breakdown: "రిస్క్ అసెస్‌మెంట్ బరువుల వివరాలు",
    hide: "దాచు",
    vectors_count: "4 వెక్టర్స్ (100%)",
    vector1_title: "1. వాయిస్ ప్రామాణికత & డీప్‌ఫేక్ టెలిమెట్రీ",
    vector1_desc: "స్పెక్ట్రల్ ఫేజ్ స్లిప్స్, ఫార్మాంట్ హార్మోనిక్స్, వొకోడర్ ఆర్టిఫాక్ట్స్, F0 జిట్టర్.",
    vector2_title: "2. పదజాలం, ఫిషింగ్ & దోపిడీ కీవర్డ్లు",
    vector2_desc: "OTP హార్వెస్టింగ్, నకిలీ అధికార అనుకరణ, బ్యాంక్ బదిలీ డిమాండ్లు.",
    vector3_title: "3. టోన్, ప్రోసోడీ & అకౌస్టిక్ ఒత్తిడి",
    vector3_desc: "స్పీచ్ టెంపో (WPM), పాజ్ కాడెన్స్, అసహజ ఏకరీతి.",
    vector4_title: "4. సందర్భోచిత అత్యవసరం & ఛానల్ ఐసోలేషన్",
    vector4_desc: "కృత్రిమ గడువులు ('15 నిమిషాల్లో'), 'నా సెల్‌కు కాల్ చేయవద్దు'.",
    composite_formula: "కాంపోజిట్ స్కోర్ ఫార్ములా:",
    weight_40: "40% బరువు",
    weight_25: "25% బరువు",
    weight_10: "10% బరువు",
    speech_to_text_title: "లైవ్ స్పీచ్-టు-టెక్స్ట్ & అనువాదం",
    speech_to_text_subtitle: "సింక్రొనైజ్డ్ మల్టీ-మోడల్ లింగ్విస్టిక్ ఇంజిన్",
    side_by_side: "పక్కపక్కనే",
    original: "అసలు",
    translation: "అనువాదం",
    original_transcript_title: "అసలు ఆడియో ట్రాన్స్క్రిప్ట్ (ఫ్లాగ్ చేయబడిన పదాలతో)",
    live_translation_title: "లైవ్ అనువాదం",
    awaiting_audio: "లైవ్ ట్రాన్స్క్రిప్షన్ కోసం ఆడియో ఫీడ్ కోసం వేచి ఉంది...",
    translating_realtime: "నిజ సమయంలో అనువదిస్తోంది...",
    translation_will_appear: "ప్రసంగం ప్రాసెస్ చేయబడినప్పుడు అనువాదం ఇక్కడ కనిపిస్తుంది...",
    copy_original: "అసలు కాపీ చేయండి",
    copy_translation: "అనువాదం కాపీ చేయండి",
    copied: "కాపీ చేయబడింది!",
    tone_telemetry_title: "టోన్ & అకౌస్టిక్ ప్రోసోడీ టెలిమెట్రీ",
    tone_telemetry_subtitle: "F0 పిచ్, ఎనర్జీ RMS, రిథమ్ & పాజ్ డిస్పర్షన్",
    acoustic_ml_badge: "Hertzy అకౌస్టిక్ ML",
    pitch_f0: "పిచ్ (F0)",
    range: "పరిధి:",
    jitter: "జిట్టర్:",
    elevated: "ఎలివేటెడ్",
    stable: "స్థిరమైనది",
    energy_level: "శక్తి స్థాయి",
    rms_headroom: "RMS డైనమిక్ హెడ్‌రూమ్",
    tone_classification: "టోన్ వర్గీకరణ",
    inferred_vocal_stance: "అనుమతించబడిన స్వర వైఖరి",
    neural_formant_analysis: "న్యూరల్ ఫార్మాంట్ విశ్లేషణ",
    prosody_rate: "ప్రోసోడీ రేటు",
    speech_flow_cadence: "స్పీచ్ ఫ్లో కాడెన్స్",
    naturalness: "సహజత్వం:",
    pause_duration: "పాజ్ వ్యవధి",
    avg_intersyllabic_gap: "సగటు సిలబిక్ గ్యాప్",
    unusually_rapid_synthetic: "⚠️ అసాధారణ వేగవంతమైన/సింథటిక్",
    natural_breathing_gap: "✓ సహజ శ్వాస గ్యాప్",
    pause_frequency: "పాజ్ ఫ్రీక్వెన్సీ",
    breathing_rate: "శ్వాస & సంకోచం రేటు",
    centroid: "సెంట్రాయిడ్:",
    suspicious_vocab_title: "అనుమానాస్పద పదజాలం & ముప్పు పదబంధాలు",
    suspicious_vocab_subtitle: "సెమాంటిక్ ఒత్తిడి & ఆర్థిక ఫిషింగ్ ఫిల్టర్",
    detected: "గుర్తించబడింది",
    all: "అన్నీ",
    category: "వర్గం:",
    no_suspicious_markers: "అనుమానాస్పద పదజాల గుర్తులు ఏవీ లేవు.",
    critical: "క్రిటికల్",
    high: "హై",
    medium: "మీడియం",
    risk_timeline_title: "రిస్క్ వర్సెస్ టైమ్ గ్రాఫ్",
    risk_timeline_subtitle: "టెంపోరల్ విండో విశ్లేషణ",
    all_metrics: "అన్ని మెట్రిక్స్",
    composite: "కాంపోజిట్",
    voice_clone: "వాయిస్ క్లోన్",
    vocabulary: "పదజాలం",
    tone_prosody: "టోన్ / ప్రోసోడీ",
    peak_voice: "పీక్ వాయిస్:",
    peak_vocab: "పీక్ పదజాలం:",
    windows_analyzed: "విశ్లేషించిన విండోలు:",
    slice_resolution: "స్లైస్ రిజల్యూషన్:",
    intervals: "వ్యవధులు",
    no_timeline_data: "టైమ్‌లైన్ డేటా లేదు. రిస్క్ ప్రొఫైల్ రూపొందించడానికి ఆడియోను అప్‌లోడ్ చేయండి.",
    ai_summary_title: "AI ఎగ్జిక్యూటివ్ రిస్క్ సారాంశం",
    ai_summary_subtitle: "సింథసైజ్డ్ మల్టీ-మోడల్ ముప్పు అసెస్‌మెంట్ (4-5 పాయింట్లు)",
    awaiting_analysis_pass: "ఆడియో విశ్లేషణ పూర్తయ్యే వరకు వేచి ఉంది.",
    copy: "కాపీ",
    export_json: "JSON ఎగుమతి",
    save_to_history: "వాల్ట్ చరిత్రలో సేవ్ చేయండి",
    saved_to_vault: "వాల్ట్‌లో సేవ్ చేయబడింది",
    delete_audio_reset: "ఆడియోను తొలగించు / రీసెట్",
    vault_history_title: "ఆడియో విశ్లేషణ వాల్ట్ చరిత్ర",
    vault_history_subtitle: "సేవ్ చేయబడిన ఆడిట్ సెషన్‌లు & రికార్డులు",
    search_history_placeholder: "శీర్షిక లేదా కీవర్డ్ ద్వారా శోధించండి...",
    export_csv: "CSV ఎగుమతి",
    clear_all: "అన్నీ క్లియర్ చేయండి",
    load: "లోడ్ చేయండి",
    delete_record: "రికార్డ్ తొలగించండి",
    no_audit_logs: "ఆడిట్ లాగ్‌లు ఏవీ లేవు. రికార్డులను చూడటానికి సెషన్‌ను సేవ్ చేయండి.",
    duration_suffix: "వ్యవధి",
    login_id_label: "లాగిన్ ID / యూజర్ ఐడెంటిఫైయర్",
    login_id_placeholder: "'demo' లేదా యూజర్ ID నమోదు చేయండి",
    security_password_label: "భద్రతా పాస్‌వర్డ్",
    default_label: "డిఫాల్ట్:",
    demo_credentials_title: "డెమో ఆధారాలు:",
    auto_fill: "ఆటో-ఫిల్",
    remember_session: "ఈ పరికరంలో సెషన్‌ను గుర్తుంచుకో",
    auth_error_title: "ధృవీకరణ లోపం",
    enter_credentials_error: "దయచేసి మీ లాగిన్ ID మరియు పాస్‌వర్డ్ నమోదు చేయండి.",
    invalid_credentials_error: "చెల్లని ఆధారాలు. 'demo' మరియు 'demo123' ఉపయోగించండి.",
    signing_in: "ధృవీకరిస్తోంది...",
    sign_in_btn: "ప్రామాణీకరించండి & వాల్ట్ తెరవండి",
    security_protocol_notice: "ఎండ్-టు-ఎండ్ క్రిప్టోగ్రాఫిక్ సమగ్రత మరియు వాయిస్ బయోమెట్రిక్ రక్షణతో భద్రపరచబడింది.",
  },
  ar: {
    app_name: "Hertzy",
    app_tagline: "لكل صوت بصمة مميزة",
    system_live: "النظام نشط",
    processing_audio: "معالجة الصوت جارية",
    light: "فاتح",
    dark: "داكن",
    lang_label: "اللغة:",
    history: "السجل",
    logged_in_as: "تم تسجيل الدخول كـ",
    sign_out: "تسجيل الخروج",
    critical_threat: "تهديد حرج",
    elevated_threat: "تهديد مرتفع",
    moderate_risk: "خطر متوسط",
    low_risk: "خطر منخفض",
    very_low_risk: "خطر منخفض جداً",
    alert_high_risk_call: "تنبيه أمني: تم رصد مكالمة صوتية عالية الخطورة — احتمال احتيال باستنساخ الصوت عبر التزييف العميق",
    alert_safe_call: "إشعار أمني: مكالمة آمنة تم التحقق منها — بصمة صوت بشرية أصلية",
    alert_cautious_call: "إشعار أمني: مكالمة تتطلب الحذر — تم رصد شذوذ صوتي أو لغوي",
    rerun_analysis: "إعادة التحليل",
    analysis_time: "وقت التحليل",
    source: "المصدر",
    file: "الملف",
    sample: "العينة",
    microphone: "الميكروفون",
    upload: "تحميل",
    temporal_window_slices: "شرائح النوافذ الزمنية:",
    window_resolution: "دقة النافذة:",
    live_microphone: "الميكروفون المباشر",
    upload_audio_file: "تحميل ملف صوتي",
    time_window: "النافذة الزمنية:",
    mic_ready: "الميكروفون جاهز",
    live_audio_capture: "التقاط الصوت المباشر جارٍ",
    mic_ready_desc: "انقر فوق الميكروفون لتسجيل الصوت المباشر. ستظهر الكلمات والقياسات الصوتية أدناه في الوقت الفعلي.",
    mic_recording_desc: "جارٍ بث العينات الصوتية إلى مصنف Hertzy اللحظي. تحدث بشكل طبيعي أو اختبر عبارات التصيد.",
    live_pitch: "طبقة الصوت المباشرة",
    live_energy: "طاقة الصوت",
    duration: "المدة",
    noise_reduction: "تقليل الضوضاء",
    rms_normalization: "معايرة RMS",
    on: "تشغيل",
    off: "إيقاف",
    live_speech_stream: "بث الكلام المباشر لحظياً:",
    listening_words: "في انتظار الكلمات المنطوقة...",
    drop_audio_here: "أفلت الملف الصوتي المسجل هنا أو",
    browse: "تصفح",
    supports_formats: "يدعم .wav, .mp3, .m4a, .ogg حتى 50 ميغابايت",
    benchmark_scenarios: "سيناريوهات الاختبار القياسي (انقر للتجربة):",
    decoded_ready: "تم فك التشفير وجاهز",
    loading_benchmark: "جارٍ تحميل السيناريو القياسي:",
    error_benchmark: "خطأ في توليد الإشارة الصوتية للسيناريو.",
    live_acoustic_graph: "الرسم الصوتي المباشر",
    streaming_active: "البث نشط",
    oscilloscope_ready: "جهاز راسم الإشارة جاهز في الوقت الفعلي",
    hybrid: "هجين",
    oscilloscope: "راسم الإشارة",
    fft_spectrum: "طيف FFT",
    signal: "الإشارة",
    standby: "في الانتظار",
    interaction_risk_gauge: "مؤشر خطر التفاعل",
    risk_index: "مؤشر الخطر",
    badge_very_low: "0-20 منخفض جداً",
    badge_low: "21-40 منخفض",
    badge_moderate: "41-60 متوسط",
    badge_elevated: "61-80 مرتفع",
    badge_high: "81-100 حرج",
    status_very_low: "خطر منخفض جداً (آمن)",
    status_low: "خطر منخفض (طبيعي)",
    status_moderate: "خطر متوسط (حذر)",
    status_elevated: "تهديد مرتفع (شاذ)",
    status_high: "تهديد خطير (احتيال تزييف عميق)",
    natural_patterns: "الأنماط الصوتية واللغوية طبيعية",
    elevated_urgency: "استعجال ملحوظ / إجهاد صوتي",
    high_confidence_deepfake: "احتمال استنساخ وتزييف عميق بثقة عالية",
    synthetic_probability: "احتمالية الصوت التخليقي في Hertzy:",
    risk_weights_breakdown: "تفصيل أوزان تقييم المخاطر",
    hide: "إخفاء",
    vectors_count: "4 محاور (100%)",
    vector1_title: "1. موثوقية الصوت وقياسات التزييف العميق",
    vector1_desc: "انزلاق الطور الطيفي، توافقيات الصوت، شوائب المشفر، تقلبات F0.",
    vector2_title: "2. المفردات والتصيد وكلمات الابتزاز",
    vector2_desc: "سرقة رموز OTP، انتحال صفة رسمية، طلبات تحويل مصرفي.",
    vector3_title: "3. النبرة والعروض والإجهاد الصوتي",
    vector3_desc: "سرعة الكلام (WPM)، وتيرة الوقفات، رتابة مصطنعة.",
    vector4_title: "4. الاستعجال السياقي وعزل القناة",
    vector4_desc: "مواعيد نهائية مصطنعة ('خلال 15 دقيقة')، 'لا تتصل بهاتفي'.",
    composite_formula: "معادلة الدرجة المركبة:",
    weight_40: "وزن 40%",
    weight_25: "وزن 25%",
    weight_10: "وزن 10%",
    speech_to_text_title: "تحويل الصوت إلى نص والترجمة الفورية",
    speech_to_text_subtitle: "محرك لغوي متعدد الوسائط متزامن",
    side_by_side: "جنباً إلى جنب",
    original: "الأصل",
    translation: "الترجمة",
    original_transcript_title: "النص الصوتي الأصلي (مع العبارات المشبوهة)",
    live_translation_title: "الترجمة المباشرة",
    awaiting_audio: "في انتظار إشارة الصوت للنسخ المباشر...",
    translating_realtime: "جارٍ الترجمة في الوقت الفعلي...",
    translation_will_appear: "ستظهر الترجمة هنا ديناميكياً أثناء معالجة الكلام...",
    copy_original: "نسخ الأصل",
    copy_translation: "نسخ الترجمة",
    copied: "تم النسخ!",
    tone_telemetry_title: "قياسات النبرة والعروض الصوتية",
    tone_telemetry_subtitle: "تردد F0، طاقة RMS، الإيقاع وتشتت الوقفات",
    acoustic_ml_badge: "Hertzy للتعلم الآلي الصوتي",
    pitch_f0: "التردد الأساسي (F0)",
    range: "النطاق:",
    jitter: "التقلب (Jitter):",
    elevated: "مرتفع",
    stable: "مستقر",
    energy_level: "مستوى الطاقة",
    rms_headroom: "مجال RMS الديناميكي",
    tone_classification: "تصنيف النبرة",
    inferred_vocal_stance: "الموقف الصوتي المستنتج",
    neural_formant_analysis: "تحليل الترددات الرنينية العصبية",
    prosody_rate: "معدل الإيقاع",
    speech_flow_cadence: "انسياب تدفق الكلام",
    naturalness: "العفوية والطبيعية:",
    pause_duration: "مدة الوقفات",
    avg_intersyllabic_gap: "متوسط الفواصل بين المقاطع",
    unusually_rapid_synthetic: "⚠️ سريع أو مصطنع بشكل غير معتاد",
    natural_breathing_gap: "✓ فاصل تنفس طبيعي",
    pause_frequency: "تكرار الوقفات",
    breathing_rate: "معدل التنفس والتردد",
    centroid: "المركز الطيفي:",
    suspicious_vocab_title: "المفردات المشبوهة وعبارات التهديد",
    suspicious_vocab_subtitle: "مرشح الإكراه الدلالي والتصيد المالي",
    detected: "تم رصدها",
    all: "الكل",
    category: "الفئة:",
    no_suspicious_markers: "لم يتم رصد أي علامات لمفردات مشبوهة.",
    critical: "حرج",
    high: "مرتفع",
    medium: "متوسط",
    risk_timeline_title: "رسم بياني للمخاطر مقابل الوقت",
    risk_timeline_subtitle: "تحليل النوافذ الزمنية",
    all_metrics: "كافة المقاييس",
    composite: "المركب",
    voice_clone: "استنساخ الصوت",
    vocabulary: "المفردات",
    tone_prosody: "النبرة / الإيقاع",
    peak_voice: "أعلى خطر صوتي:",
    peak_vocab: "أعلى خطر لغوي:",
    windows_analyzed: "النوافذ المحللة:",
    slice_resolution: "دقة الشريحة:",
    intervals: "فترات",
    no_timeline_data: "لا توجد بيانات زمنية. حمّل ملفاً أو سجل بالميكروفون لتوليد المخطط.",
    ai_summary_title: "الملخص التنفيذي للمخاطر بالذكاء الاصطناعي",
    ai_summary_subtitle: "تقييم التهديدات متعدد الوسائط المجمع (تحليل من 4-5 نقاط)",
    awaiting_analysis_pass: "توليف المخاطر في انتظار اكتمال دورة التحليل الصوتي.",
    copy: "نسخ",
    export_json: "تصدير JSON",
    save_to_history: "حفظ في سجل الخزينة",
    saved_to_vault: "محفوظ في الخزينة",
    delete_audio_reset: "حذف الصوت / إعادة ضبط",
    vault_history_title: "سجل خزينة التحليلات الصوتية",
    vault_history_subtitle: "جلسات التدقيق المحفوظة وسجلات القياسات الصوتية",
    search_history_placeholder: "ابحث في الجلسات حسب العنوان أو الكلمات المفتاحية...",
    export_csv: "تصدير CSV",
    clear_all: "مسح الكل",
    load: "تحميل",
    delete_record: "حذف السجل",
    no_audit_logs: "لا توجد سجلات تدقيق. احفظ جلسة محللة لعرض السجلات هنا.",
    duration_suffix: "المدة",
    login_id_label: "معرف الدخول / اسم المستخدم",
    login_id_placeholder: "أدخل 'demo' أو معرف المستخدم",
    security_password_label: "كلمة المرور الأمنية",
    default_label: "الافتراضي:",
    demo_credentials_title: "بيانات التجربة المعتمدة:",
    auto_fill: "إكمال تلقائي",
    remember_session: "تذكر الجلسة على هذا الجهاز",
    auth_error_title: "خطأ في المصادقة",
    enter_credentials_error: "يرجى إدخال اسم المستخدم وكلمة المرور للمصادقة.",
    invalid_credentials_error: "بيانات الاعتماد غير صالحة. استخدم 'demo' و 'demo123'.",
    signing_in: "جارٍ التحقق...",
    sign_in_btn: "المصادقة والوصول إلى الخزينة",
    security_protocol_notice: "محمي بتشفير شامل، وحماية القياسات الحيوية للصوت، وسجلات تدقيق معزولة.",
  },
  bn: {
    app_name: "Hertzy",
    app_tagline: "প্রতিটি কণ্ঠস্বরের একটি নিজস্ব স্বাক্ষর থাকে",
    system_live: "সিস্টেম সক্রিয়",
    processing_audio: "অডিও প্রক্রিয়াকরণ চলছে",
    light: "লাইট",
    dark: "ডার্ক",
    lang_label: "ভাষা:",
    history: "ইতিহাস",
    logged_in_as: "লগইন আছেন:",
    sign_out: "সাইন আউট",
    critical_threat: "মারাত্মক হুমকি",
    elevated_threat: "উচ্চ হুমকি",
    moderate_risk: "মাঝারি ঝুঁকি",
    low_risk: "কম ঝুঁকি",
    very_low_risk: "খুব কম ঝুঁকি",
    alert_high_risk_call: "নিরাপত্তা সতর্কতা: উচ্চ ঝুঁকিপূর্ণ ভয়েস কল শনাক্ত — সম্ভাব্য ডিপফেক ভয়েস ক্লোন কেলেঙ্কারি",
    alert_safe_call: "নিরাপত্তা বিজ্ঞপ্তি: যাচাইকৃত নিরাপদ কল — খাঁটি মানব কণ্ঠস্বর",
    alert_cautious_call: "নিরাপত্তা বিজ্ঞপ্তি: সতর্কতামূলক কল — ধ্বনি বা শব্দভাণ্ডারে অসঙ্গতি শনাক্ত",
    rerun_analysis: "পুনরায় বিশ্লেষণ চালান",
    analysis_time: "বিশ্লেষণের সময়",
    source: "উৎস",
    file: "ফাইল",
    sample: "নমুনা",
    microphone: "মাইক্রোফোন",
    upload: "আপলোড",
    temporal_window_slices: "সময় উইন্ডো স্লাইস:",
    window_resolution: "উইন্ডো রেজোলিউশন:",
    live_microphone: "লাইভ মাইক্রোফোন",
    upload_audio_file: "অডিও ফাইল আপলোড করুন",
    time_window: "সময় উইন্ডো:",
    mic_ready: "মাইক্রোফোন প্রস্তুত",
    live_audio_capture: "লাইভ অডিও ক্যাপচার চলছে",
    mic_ready_desc: "লাইভ কথা রেকর্ড করতে মাইক্রোফোনে ক্লিক করুন। রিয়েল-টাইম শব্দ এবং অ্যাকোস্টিক টেলিমেট্রি নিচে দেখা যাবে।",
    mic_recording_desc: "Hertzy রিয়েল-টাইম ক্লাসিফায়ারে অ্যাকোস্টিক নমুনা পাঠানো হচ্ছে। স্বাভাবিকভাবে কথা বলুন।",
    live_pitch: "লাইভ পিচ",
    live_energy: "লাইভ শক্তি",
    duration: "সময়কাল",
    noise_reduction: "শব্দ হ্রাস",
    rms_normalization: "RMS স্বাভাবিকীকরণ",
    on: "চালু",
    off: "বন্ধ",
    live_speech_stream: "লাইভ রিয়েল-টাইম স্পিচ স্ট্রিম:",
    listening_words: "কথার শব্দের জন্য অপেক্ষা করা হচ্ছে...",
    drop_audio_here: "রেকর্ড করা অডিও ফাইল এখানে ফেলুন অথবা",
    browse: "ব্রাউজ করুন",
    supports_formats: ".wav, .mp3, .m4a, .ogg (সর্বোচ্চ 50MB পর্যন্ত সমর্থিত)",
    benchmark_scenarios: "বেঞ্চমার্ক অডিও পরিস্থিতি (পরীক্ষার জন্য ক্লিক করুন):",
    decoded_ready: "ডিকোড ও প্রস্তুত",
    loading_benchmark: "বেঞ্চমার্ক পরিস্থিতি লোড হচ্ছে:",
    error_benchmark: "বেঞ্চমার্ক অ্যাকোস্টিক সিগন্যাল তৈরিতে ত্রুটি।",
    live_acoustic_graph: "লাইভ অ্যাকোস্টিক গ্রাফ",
    streaming_active: "স্ট্রিমিং সক্রিয়",
    oscilloscope_ready: "রিয়েল-টাইম অসিলোস্কোপ প্রস্তুত",
    hybrid: "হাইব্রিড",
    oscilloscope: "অসিলোস্কোপ",
    fft_spectrum: "FFT স্পেকট্রাম",
    signal: "সিগন্যাল",
    standby: "স্ট্যান্ডবাই",
    interaction_risk_gauge: "ইন্টারঅ্যাকশন ঝুঁকি গেজ",
    risk_index: "ঝুঁকি সূচক",
    badge_very_low: "0-20 খুব কম",
    badge_low: "21-40 কম",
    badge_moderate: "41-60 মাঝারি",
    badge_elevated: "61-80 উচ্চ",
    badge_high: "81-100 মারাত্মক",
    status_very_low: "খুব কম ঝুঁকি (নিরাপদ)",
    status_low: "কম ঝুঁকি (স্বাভাবিক)",
    status_moderate: "মাঝারি ঝুঁকি (সতর্কতা)",
    status_elevated: "উচ্চ ঝুঁকি (অস্বাভাবিক)",
    status_high: "মারাত্মক হুমকি (ডিপফেক কেলেঙ্কারি)",
    natural_patterns: "ধ্বনি ও শব্দভাণ্ডার প্যাটার্ন স্বাভাবিক",
    elevated_urgency: "অস্বাভাবিক তাড়াহুড়ো / কণ্ঠে চাপ",
    high_confidence_deepfake: "উচ্চ নিশ্চিততার ডিপফেক ছদ্মবেশ",
    synthetic_probability: "Hertzy কৃত্রিম সম্ভাব্যতা:",
    risk_weights_breakdown: "ঝুঁকি মূল্যায়ন ওজনের বিভাজন",
    hide: "লুকান",
    vectors_count: "৪টি ভেক্টর (১০০%)",
    vector1_title: "১. ভয়েস সত্যতা ও ডিপফেক টেলিমেট্রি",
    vector1_desc: "স্পেকট্রাল ফেজ স্লিপ, ফরম্যান্ট হারমোনিক্স, ভোকোডার ত্রুটি, F0 জিটার।",
    vector2_title: "২. শব্দভাণ্ডার, ফিশিং ও চাঁদাবাজি কীওয়ার্ড",
    vector2_desc: "ওটিপি চুরি, ভুয়া কর্মকর্তা ছদ্মবেশ, ব্যাংক স্থানান্তরের দাবি।",
    vector3_title: "৩. সুর, প্রসোডি ও অ্যাকোস্টিক চাপ",
    vector3_desc: "কথার গতি (WPM), বিরতির ছন্দ, অস্বাভাবিক একঘেয়েমি।",
    vector4_title: "৪. প্রাসঙ্গিক জরুরি অবস্থা ও যোগাযোগ বিচ্ছিন্নতা",
    vector4_desc: "কৃত্রিম সময়সীমা ('১৫ মিনিটের মধ্যে'), 'আমার ফোনে কল করবেন না'।",
    composite_formula: "যৌগিক স্কোর সূত্র:",
    weight_40: "৪০% ওজন",
    weight_25: "২৫% ওজন",
    weight_10: "১০% ওজন",
    speech_to_text_title: "লাইভ স্পিচ-টু-টেক্সট ও অনুবাদ",
    speech_to_text_subtitle: "সিঙ্ক্রোনাইজড মাল্টি-মডেল ভাষাগত ইঞ্জিন",
    side_by_side: "পাশাপাশি",
    original: "মূল",
    translation: "অনুবাদ",
    original_transcript_title: "মূল অডিও প্রতিলিপি (চিহ্নিত শব্দসহ)",
    live_translation_title: "লাইভ অনুবাদ",
    awaiting_audio: "লাইভ প্রতিলিপির জন্য অডিও ফিডের অপেক্ষা...",
    translating_realtime: "রিয়েল-টাইমে অনুবাদ করা হচ্ছে...",
    translation_will_appear: "কথা প্রক্রিয়া হওয়ার সাথে সাথে অনুবাদ এখানে প্রদর্শিত হবে...",
    copy_original: "মূল কপি করুন",
    copy_translation: "অনুবাদ কপি করুন",
    copied: "কপি হয়েছে!",
    tone_telemetry_title: "স্বর ও অ্যাকোস্টিক প্রসোডি টেলিমেট্রি",
    tone_telemetry_subtitle: "F0 পিচ, এনার্জি RMS, ছন্দ ও বিরতি বিচ্ছুরণ",
    acoustic_ml_badge: "Hertzy অ্যাকোস্টিক ML",
    pitch_f0: "পিচ (F0)",
    range: "পরিসীমা:",
    jitter: "জিটার:",
    elevated: "উচ্চ",
    stable: "স্থিতিশীল",
    energy_level: "শক্তির স্তর",
    rms_headroom: "RMS ডায়নামিক হেডরুম",
    tone_classification: "সুর শ্রেণিবিভাগ",
    inferred_vocal_stance: "অনুমানকৃত কণ্ঠভঙ্গি",
    neural_formant_analysis: "নিউরাল ফরম্যান্ট বিশ্লেষণ",
    prosody_rate: "প্রসোডি হার",
    speech_flow_cadence: "কথার প্রবাহের ছন্দ",
    naturalness: "স্বাভাবিকতা:",
    pause_duration: "বিরতি সময়কাল",
    avg_intersyllabic_gap: "গড় শব্দাংশ বিরতি",
    unusually_rapid_synthetic: "⚠️ অস্বাভাবিক দ্রুত/কৃত্রিম",
    natural_breathing_gap: "✓ স্বাভাবিক শ্বাসপ্রশ্বাসের বিরতি",
    pause_frequency: "বিরতির পুনরাবৃত্তি",
    breathing_rate: "শ্বাস ও দ্বিধার হার",
    centroid: "সেন্ট্রয়েড:",
    suspicious_vocab_title: "সন্দেহজনক শব্দভাণ্ডার ও হুমকি বাক্যাংশ",
    suspicious_vocab_subtitle: "অর্থনৈতিক ফিশিং ও জবরদস্তি ফিল্টার",
    detected: "শনাক্ত",
    all: "সব",
    category: "বিভাগ:",
    no_suspicious_markers: "কোনো সন্দেহজনক শব্দভাণ্ডার চিহ্নিত হয়নি।",
    critical: "মারাত্মক",
    high: "উচ্চ",
    medium: "মাঝারি",
    risk_timeline_title: "ঝুঁকি বনাম সময় গ্রাফ",
    risk_timeline_subtitle: "সময় উইন্ডো বিশ্লেষণ",
    all_metrics: "সব মেট্রিক্স",
    composite: "যৌগিক",
    voice_clone: "ভয়েস ক্লোন",
    vocabulary: "শব্দভাণ্ডার",
    tone_prosody: "সুর / প্রসোডি",
    peak_voice: "শীর্ষ ভয়েস:",
    peak_vocab: "শীর্ষ শব্দভাণ্ডার:",
    windows_analyzed: "বিশ্লেষিত উইন্ডো:",
    slice_resolution: "স্লাইস রেজোলিউশন:",
    intervals: "ব্যবধান",
    no_timeline_data: "কোনো টাইমলাইন তথ্য নেই। ঝুঁকি প্রোফাইল তৈরি করতে অডিও আপলোড করুন।",
    ai_summary_title: "AI নির্বাহী ঝুঁকি সারাংশ",
    ai_summary_subtitle: "সংশ্লেষিত মাল্টি-মডেল হুমকি মূল্যায়ন (৪-৫ পয়েন্ট বিশ্লেষণ)",
    awaiting_analysis_pass: "অডিও বিশ্লেষণ সম্পন্ন হওয়ার অপেক্ষায় রয়েছে।",
    copy: "কপি",
    export_json: "JSON এক্সপোর্ট",
    save_to_history: "ভল্ট ইতিহাসে সংরক্ষণ করুন",
    saved_to_vault: "ভল্টে সংরক্ষিত",
    delete_audio_reset: "অডিও মুছুন / রিসেট",
    vault_history_title: "অডিও বিশ্লেষণ ভল্ট ইতিহাস",
    vault_history_subtitle: "সংরক্ষিত অডিট সেশন ও অ্যাকোস্টিক রেকর্ড",
    search_history_placeholder: "শিরোনাম বা কীওয়ার্ড দ্বারা সেশন অনুসন্ধান করুন...",
    export_csv: "CSV এক্সপোর্ট",
    clear_all: "সব মুছুন",
    load: "লোড",
    delete_record: "রেকর্ড মুছুন",
    no_audit_logs: "কোনো অডিট লগ পাওয়া যায়নি। রেকর্ড দেখতে সেশন সংরক্ষণ করুন।",
    duration_suffix: "সময়কাল",
    login_id_label: "লগইন আইডি / ব্যবহারকারী শনাক্তকারী",
    login_id_placeholder: "'demo' বা ব্যবহারকারী আইডি দিন",
    security_password_label: "নিরাপত্তা পাসওয়ার্ড",
    default_label: "ডিফল্ট:",
    demo_credentials_title: "ডেমো তথ্য:",
    auto_fill: "স্বয়ংক্রিয় পূরণ",
    remember_session: "এই ডিভাইসে সেশন মনে রাখুন",
    auth_error_title: "প্রমাণীকরণ ত্রুটি",
    enter_credentials_error: "অনুগ্রহ করে আপনার লগইন আইডি এবং পাসওয়ার্ড দিন।",
    invalid_credentials_error: "ভুল তথ্য। 'demo' এবং 'demo123' ব্যবহার করুন।",
    signing_in: "যাচাই করা হচ্ছে...",
    sign_in_btn: "প্রমাণীকরণ করুন ও ভল্ট খুলুন",
    security_protocol_notice: "এন্ড-টু-এন্ড ক্রিপ্টোগ্রাফিক সুরক্ষা এবং ভয়েস বায়োমেট্রিক সুরক্ষার মাধ্যমে সুরক্ষিত।",
  },
  mr: {
    app_name: "Hertzy",
    app_tagline: "प्रत्येक आवाजाची एक स्वाक्षरी असते",
    system_live: "सिस्टम थेट सुरू आहे",
    processing_audio: "ऑडिओ प्रक्रिया चालू आहे",
    light: "लाइट",
    dark: "डार्क",
    lang_label: "भाषा:",
    history: "इतिहास",
    logged_in_as: "लॉग इन:",
    sign_out: "साइन आउट",
    critical_threat: "गंभीर धोका",
    elevated_threat: "वाढलेला धोका",
    moderate_risk: "मध्यम जोखीम",
    low_risk: "कमी जोखीम",
    very_low_risk: "अतिशय कमी जोखीम",
    alert_high_risk_call: "सुरक्षा इशारा: उच्च जोखमीचा व्हॉइस कॉल आढळला — संभाव्य डीपफेक व्हॉइस क्लोन फसवणूक",
    alert_safe_call: "सुरक्षा सूचना: सुरक्षित कॉल सत्यापित — अस्सल मानवी आवाज",
    alert_cautious_call: "सुरक्षा सूचना: सतर्क कॉल — ध्वनिक किंवा शब्दसंग्रहात विसंगती आढळली",
    rerun_analysis: "पुन्हा विश्लेषण करा",
    analysis_time: "विश्लेषण वेळ",
    source: "स्रोत",
    file: "फाइल",
    sample: "नमुना",
    microphone: "मायक्रोफोन",
    upload: "अपलोड",
    temporal_window_slices: "वेळ विंडो स्लाइस:",
    window_resolution: "विंडो रिझोल्यूशन:",
    live_microphone: "थेट मायक्रोफोन",
    upload_audio_file: "ऑडिओ फाइल अपलोड करा",
    time_window: "वेळ विंडो:",
    mic_ready: "मायक्रोफोन सज्ज आहे",
    live_audio_capture: "थेट ऑडिओ रेकॉर्डिंग सुरू आहे",
    mic_ready_desc: "थेट संभाषण रेकॉर्ड करण्यासाठी मायक्रोफोनवर क्लिक करा. रिअल-टाइम शब्द आणि ध्वनिक टेलिमेट्री खाली दिसेल.",
    mic_recording_desc: "Hertzy रिअल-टाइम क्लासिफायरकडे ध्वनिक नमुने पाठवले जात आहेत. स्वाभाविकपणे बोला.",
    live_pitch: "थेट पिच",
    live_energy: "थेट ऊर्जा",
    duration: "कालावधी",
    noise_reduction: "आवाज कमी करणे",
    rms_normalization: "RMS सामान्यीकरण",
    on: "सुरू",
    off: "बंद",
    live_speech_stream: "थेट रिअल-टाइम भाषण प्रवाह:",
    listening_words: "बोललेल्या शब्दांची प्रतीक्षा...",
    drop_audio_here: "रेकॉर्ड केलेली ऑडिओ फाइल येथे टाका किंवा",
    browse: "ब्राउझ करा",
    supports_formats: ".wav, .mp3, .m4a, .ogg (कमाल 50MB पर्यंत)",
    benchmark_scenarios: "बेंचमार्क ऑडिओ परिस्थिती (चाचणीसाठी क्लिक करा):",
    decoded_ready: "डीकोड व तयार",
    loading_benchmark: "बेंचमार्क परिस्थिती लोड होत आहे:",
    error_benchmark: "बेंचमार्क ध्वनिक सिग्नल तयार करण्यात त्रुटी.",
    live_acoustic_graph: "थेट ध्वनिक आलेख",
    streaming_active: "प्रवाह सक्रिय",
    oscilloscope_ready: "रिअल-टाइम ऑसिलोस्कोप सज्ज",
    hybrid: "हायब्रिड",
    oscilloscope: "ऑसिलोस्कोप",
    fft_spectrum: "FFT स्पेक्ट्रम",
    signal: "सिग्नल",
    standby: "स्टँडबाय",
    interaction_risk_gauge: "संभाषण जोखीम मापक",
    risk_index: "जोखीम निर्देशांक",
    badge_very_low: "0-20 अतिशय कमी",
    badge_low: "21-40 कमी",
    badge_moderate: "41-60 मध्यम",
    badge_elevated: "61-80 वाढलेला",
    badge_high: "81-100 उच्च",
    status_very_low: "अतिशय कमी जोखीम (सुरक्षित)",
    status_low: "कमी जोखीम (सामान्य)",
    status_moderate: "मध्यम जोखीम (सावधगिरी)",
    status_elevated: "वाढलेला धोका (विसंगत)",
    status_high: "उच्च धोका (डीपफेक फसवणूक)",
    natural_patterns: "ध्वनिक आणि शब्दसंग्रह नमुने नैसर्गिक आहेत",
    elevated_urgency: "अवाजवी घाई / आवाजातील ताण",
    high_confidence_deepfake: "उच्च विश्वास डीपफेक तोतयागिरी",
    synthetic_probability: "Hertzy कृत्रिम संभाव्यता:",
    risk_weights_breakdown: "जोखीम मूल्यांकन भाराचे तपशील",
    hide: "लपवा",
    vectors_count: "4 घटक (100%)",
    vector1_title: "1. आवाज सत्यता आणि डीपफेक टेलिमेट्री",
    vector1_desc: "स्पेक्ट्रल फेज स्लिप्स, फॉर्मंट हार्मोनिक्स, व्होकोडर त्रुटी, F0 जिटर.",
    vector2_title: "2. शब्दसंग्रह, फिशिंग आणि खंडणीचे शब्द",
    vector2_desc: "ओटीपी गोळा करणे, बनावट अधिकारी तोतयागिरी, बँक हस्तांतरण मागणी.",
    vector3_title: "3. टोन, प्रोसोडी आणि ध्वनिक ताण",
    vector3_desc: "भाषणाचा वेग (WPM), अक्षरांमधील विराम लय, अस्वाभाविक एकसुरीपणा.",
    vector4_title: "4. संदर्भातील तात्काळ निकड आणि संपर्क तोडणे",
    vector4_desc: "कृत्रिम मुदत ('15 मिनिटांत'), 'माझ्या फोनवर कॉल करू नका'.",
    composite_formula: "संयुक्त स्कोअर सूत्र:",
    weight_40: "40% भार",
    weight_25: "25% भार",
    weight_10: "10% भार",
    speech_to_text_title: "थेट भाषण-ते-मजकूर आणि भाषांतर",
    speech_to_text_subtitle: "सिंक्रोनाइझ केलेले मल्टी-मॉडल भाषा इंजिन",
    side_by_side: "शेजारी शेजारी",
    original: "मूळ",
    translation: "भाषांतर",
    original_transcript_title: "मूळ ऑडिओ उतारा (फ्लॅग केलेल्या वाक्यांसह)",
    live_translation_title: "थेट भाषांतर",
    awaiting_audio: "थेट लिप्यंतरणासाठी ऑडिओ फीडची प्रतीक्षा...",
    translating_realtime: "रिअल-टाइममध्ये भाषांतर होत आहे...",
    translation_will_appear: "भाषण प्रक्रिया झाल्यावर भाषांतर येथे दिसेल...",
    copy_original: "मूळ कॉपी करा",
    copy_translation: "भाषांतर कॉपी करा",
    copied: "कॉपी झाले!",
    tone_telemetry_title: "टोन आणि ध्वनिक प्रोसोडी टेलिमेट्री",
    tone_telemetry_subtitle: "F0 पिच, एनर्जी RMS, लय आणि विराम वितरण",
    acoustic_ml_badge: "Hertzy ध्वनिक ML",
    pitch_f0: "पिच (F0)",
    range: "कक्षा:",
    jitter: "जिटर:",
    elevated: "वाढलेला",
    stable: "स्थिर",
    energy_level: "ऊर्जा पातळी",
    rms_headroom: "RMS डायनॅमिक हेडरूम",
    tone_classification: "टोन वर्गीकरण",
    inferred_vocal_stance: "अनुमानित स्वर पवित्रा",
    neural_formant_analysis: "न्यूरल फॉर्मंट विश्लेषण",
    prosody_rate: "प्रोसोडी दर",
    speech_flow_cadence: "भाषण प्रवाहाची लय",
    naturalness: "स्वाभाविकता:",
    pause_duration: "विराम कालावधी",
    avg_intersyllabic_gap: "सरासरी शब्दांमधील अंतर",
    unusually_rapid_synthetic: "⚠️ असामान्यपणे वेगवान/कृत्रिम",
    natural_breathing_gap: "✓ नैसर्गिक श्वास घेण्याचा विराम",
    pause_frequency: "विराम वारंवारता",
    breathing_rate: "श्वास आणि संकोच दर",
    centroid: "सेंट्रॉइड:",
    suspicious_vocab_title: "संशयास्पद शब्दसंग्रह आणि धोक्याचे वाक्यांश",
    suspicious_vocab_subtitle: "सिमँटिक सक्ती आणि आर्थिक फिशिंग फिल्टर",
    detected: "आढळले",
    all: "सर्व",
    category: "वर्ग:",
    no_suspicious_markers: "कोणतेही संशयास्पद शब्द आढळले नाहीत.",
    critical: "गंभीर",
    high: "उच्च",
    medium: "मध्यम",
    risk_timeline_title: "जोखीम विरुद्ध वेळ आलेख",
    risk_timeline_subtitle: "वेळ विंडो विश्लेषण",
    all_metrics: "सर्व मेट्रिक्स",
    composite: "संयुक्त",
    voice_clone: "व्हॉइस क्लोन",
    vocabulary: "शब्दसंग्रह",
    tone_prosody: "टोन / प्रोसोडी",
    peak_voice: "कमाल आवाज जोखीम:",
    peak_vocab: "कमाल शब्द जोखीम:",
    windows_analyzed: "विश्लेषित विंडो:",
    slice_resolution: "स्लाइस रिझोल्यूशन:",
    intervals: "अंतराल",
    no_timeline_data: "कोणतीही टाइमलाइन माहिती उपलब्ध नाही. जोखीम प्रोफाइलसाठी ऑडिओ अपलोड करा.",
    ai_summary_title: "AI कार्यकारी जोखीम सारांश",
    ai_summary_subtitle: "संश्लेषित मल्टी-मॉडल धोका मूल्यांकन (4-5 मुद्दे विश्लेषण)",
    awaiting_analysis_pass: "ऑडिओ विश्लेषण पूर्ण होण्याची प्रतीक्षा आहे.",
    copy: "कॉपी करा",
    export_json: "JSON निर्यात करा",
    save_to_history: "वॉल्ट इतिहासामध्ये जतन करा",
    saved_to_vault: "वॉल्टमध्ये सुरक्षित",
    delete_audio_reset: "ऑडिओ हटवा / रीसेट करा",
    vault_history_title: "ऑडिओ विश्लेषण वॉल्ट इतिहास",
    vault_history_subtitle: "जतन केलेली ऑडिट सत्रे आणि ध्वनिक नोंदी",
    search_history_placeholder: "शीर्षक किंवा कीवर्डद्वारे सत्र शोधा...",
    export_csv: "CSV निर्यात करा",
    clear_all: "सर्व साफ करा",
    load: "लोड करा",
    delete_record: "नोंद हटवा",
    no_audit_logs: "कोणत्याही नोंदी आढळल्या नाहीत. नोंदी पाहण्यासाठी सत्र जतन करा.",
    duration_suffix: "कालावधी",
    login_id_label: "लॉगिन आयडी / वापरकर्ता ओळख",
    login_id_placeholder: "'demo' किंवा वापरकर्ता आयडी टाका",
    security_password_label: "सुरक्षा पासवर्ड",
    default_label: "डीफॉल्ट:",
    demo_credentials_title: "डेमो क्रेडेन्शियल्स:",
    auto_fill: "स्वयं-भरा",
    remember_session: "या डिव्हाइसवर सत्र लक्षात ठेवा",
    auth_error_title: "प्रमाणीकरण त्रुटी",
    enter_credentials_error: "कृपया आपला लॉगिन आयडी आणि पासवर्ड प्रविष्ट करा.",
    invalid_credentials_error: "अवैध माहिती. 'demo' आणि 'demo123' वापरा.",
    signing_in: "प्रमाणीकरण चालू आहे...",
    sign_in_btn: "प्रमाणीकृत करा आणि वॉल्ट उघडा",
    security_protocol_notice: "एंड-टू-एंड क्रिप्टोग्राफिक सुरक्षा आणि व्हॉइस बायोमेट्रिक संरक्षणासह सुरक्षित.",
  },
  ta: {
    app_name: "Hertzy",
    app_tagline: "ஒவ்வொரு குரலுக்கும் ஒரு கையொப்பம் உண்டு",
    system_live: "அமைப்பு நேரலையில் உள்ளது",
    processing_audio: "ஆடியோ செயலாக்கம் நடக்கிறது",
    light: "லைட்",
    dark: "டார்க்",
    lang_label: "மொழி:",
    history: "வரலாறு",
    logged_in_as: "உள்நுழைந்துள்ள கணக்கு:",
    sign_out: "வெளியேறு",
    critical_threat: "முக்கிய அச்சுறுத்தல்",
    elevated_threat: "அதிகரித்த அச்சுறுத்தல்",
    moderate_risk: "மிதமான ஆபத்து",
    low_risk: "குறைந்த ஆபத்து",
    very_low_risk: "மிகக் குறைந்த ஆபத்து",
    alert_high_risk_call: "பாதுகாப்பு எச்சரிக்கை: அதிக ஆபத்துள்ள குரல் அழைப்பு கண்டறியப்பட்டது — சாத்தியமான டீப்ஃபேக் குரல் குளோன் மோசடி",
    alert_safe_call: "பாதுகாப்பு அறிவிப்பு: சரிபார்க்கப்பட்ட பாதுகாப்பான அழைப்பு — உண்மையான மனிதக் குரல் கையொப்பம்",
    alert_cautious_call: "பாதுகாப்பு அறிவிப்பு: எச்சரிக்கை அழைப்பு — ஒலி அல்லது சொற்களஞ்சிய முரண்பாடுகள் கண்டறியப்பட்டன",
    rerun_analysis: "மீண்டும் பகுப்பாய்வு செய்",
    analysis_time: "பகுப்பாய்வு நேரம்",
    source: "மூலம்",
    file: "கோப்பு",
    sample: "மாதிரி",
    microphone: "மைக்ரோஃபோன்",
    upload: "பதிவேற்று",
    temporal_window_slices: "கால சாளர துண்டுகள்:",
    window_resolution: "சாளர தெளிவுத்திறன்:",
    live_microphone: "நேரலை மைக்ரோஃபோன்",
    upload_audio_file: "ஆடியோ கோப்பைப் பதிவேற்றவும்",
    time_window: "நேர சாளரம்:",
    mic_ready: "மைக்ரோஃபோன் தயாராக உள்ளது",
    live_audio_capture: "நேரலை ஆடியோ பதிவு நடக்கிறது",
    mic_ready_desc: "நேரலை பேச்சைப் பதிவு செய்ய மைக்ரோஃபோனைக் கிளிக் செய்யவும். நிகழ்நேர சொற்கள் கீழே காண்பிக்கப்படும்.",
    mic_recording_desc: "Hertzy நிகழ்நேர வகைப்படுத்திக்கு ஒலி மாதிரிகள் அனுப்பப்படுகின்றன. இயல்பாகப் பேசுங்கள்.",
    live_pitch: "நேரலை பிட்ச்",
    live_energy: "நேரலை ஆற்றல்",
    duration: "கால அளவு",
    noise_reduction: "சத்தம் குறைப்பு",
    rms_normalization: "RMS இயல்பாக்கம்",
    on: "இயக்கத்தில்",
    off: "முடக்கப்பட்டது",
    live_speech_stream: "நேரலை நிகழ்நேர பேச்சு ஸ்ட்ரீம்:",
    listening_words: "பேசப்படும் சொற்களுக்காகக் கேட்கிறது...",
    drop_audio_here: "பதிவுசெய்த ஆடியோ கோப்பை இங்கே விடவும் அல்லது",
    browse: "உலாவுக",
    supports_formats: ".wav, .mp3, .m4a, .ogg (50MB வரை ஆதரிக்கப்படும்)",
    benchmark_scenarios: "தரநிலைக் குரல் மாதிரிகள் (சோதிக்க கிளிக் செய்க):",
    decoded_ready: "டிகோட் செய்யப்பட்டு தயார்",
    loading_benchmark: "மாதிரி ஏற்றப்படுகிறது:",
    error_benchmark: "மாதிரி ஒலி சமிக்ஞையை உருவாக்குவதில் பிழை.",
    live_acoustic_graph: "நேரலை ஒலி வரைபடம்",
    streaming_active: "ஸ்ட்ரீமிங் செயலில் உள்ளது",
    oscilloscope_ready: "நிகழ்நேர அலைக்காட்டி தயார்",
    hybrid: "ஹைப்ரிட்",
    oscilloscope: "அலைக்காட்டி",
    fft_spectrum: "FFT ஸ்பெக்ட்ரம்",
    signal: "சமிக்ஞை",
    standby: "காத்திருப்பு",
    interaction_risk_gauge: "உரையாடல் ஆபத்து அளவுகோல்",
    risk_index: "ஆபத்து குறியீடு",
    badge_very_low: "0-20 மிகக் குறைவு",
    badge_low: "21-40 குறைவு",
    badge_moderate: "41-60 மிதமானது",
    badge_elevated: "61-80 அதிகரித்தது",
    badge_high: "81-100 அதிகம்",
    status_very_low: "மிகக் குறைந்த ஆபத்து (பாதுகாப்பானது)",
    status_low: "குறைந்த ஆபத்து (இயல்பானது)",
    status_moderate: "மிதமான ஆபத்து (எச்சரிக்கை)",
    status_elevated: "அதிகரித்த அச்சுறுத்தல் (முரண்பாடானது)",
    status_high: "அதிக அச்சுறுத்தல் (டீப்ஃபேக் மோசடி)",
    natural_patterns: "ஒலியியல் மற்றும் சொற்களஞ்சிய வடிவங்கள் இயல்பானவை",
    elevated_urgency: "அதிகரித்த அவசரம் / குரல் அழுத்தம்",
    high_confidence_deepfake: "அதிக நம்பகத்தன்மை கொண்ட டீப்ஃபேக் ஆள்மாறாட்டம்",
    synthetic_probability: "Hertzy செயற்கை குரல் நிகழ்தகவு:",
    risk_weights_breakdown: "ஆபத்து மதிப்பீட்டு எடைகளின் விவரம்",
    hide: "மறை",
    vectors_count: "4 வெக்டார்கள் (100%)",
    vector1_title: "1. குரல் உண்மைத்தன்மை மற்றும் டீப்ஃபேக் தொலைஅளவியல்",
    vector1_desc: "ஸ்பெக்ட்ரல் கட்ட நழுவல்கள், ஹார்மோனிக்ஸ், வோகோடர் பிழைகள், F0 நடுக்கம்.",
    vector2_title: "2. சொற்களஞ்சியம், ஃபிஷிங் மற்றும் மிரட்டல் சொற்கள்",
    vector2_desc: "OTP சேகரிப்பு, போலி அதிகாரி ஆள்மாறாட்டம், வங்கி பரிமாற்ற கோரிக்கைகள்.",
    vector3_title: "3. தொனி, ஓசை நயம் மற்றும் ஒலி அழுத்தம்",
    vector3_desc: "பேச்சு வேகம் (WPM), இடைநிறுத்த இசைவு, இயல்பற்ற ஒரே தொனி.",
    vector4_title: "4. சூழல் அவசரம் மற்றும் தொடர்பு தனிமைப்படுத்தல்",
    vector4_desc: "செயற்கை காலக்கெடு ('15 நிமிடங்களுக்குள்'), 'என் மொபைலுக்கு அழைக்காதீர்கள்'.",
    composite_formula: "கூட்டு மதிப்பெண் சூத்திரம்:",
    weight_40: "40% எடை",
    weight_25: "25% எடை",
    weight_10: "10% எடை",
    speech_to_text_title: "நேரலை பேச்சு-க்கு-உரை & மொழிபெயர்ப்பு",
    speech_to_text_subtitle: "ஒருங்கிணைக்கப்பட்ட பல மாதிரி மொழி இயந்திரம்",
    side_by_side: "பக்கவாட்டில்",
    original: "அசல்",
    translation: "மொழிபெயர்ப்பு",
    original_transcript_title: "அசல் ஆடியோ உரை (குறிக்கப்பட்ட சொற்றொடர்களுடன்)",
    live_translation_title: "நேரலை மொழிபெயர்ப்பு",
    awaiting_audio: "நேரலை உரைபெயர்ப்பிற்கு ஆடியோவிற்காகக் காத்திருக்கிறது...",
    translating_realtime: "நிகழ்நேரத்தில் மொழிபெயர்க்கப்படுகிறது...",
    translation_will_appear: "பேச்சு செயலாக்கப்படும் போது மொழிபெயர்ப்பு இங்கே தோன்றும்...",
    copy_original: "அசலை நகலெடு",
    copy_translation: "மொழிபெயர்ப்பை நகலெடு",
    copied: "நகலெடுக்கப்பட்டது!",
    tone_telemetry_title: "தொனி மற்றும் ஒலி ஓசை தொலைஅளவியல்",
    tone_telemetry_subtitle: "F0 பிட்ச், எனர்ஜி RMS, தாளம் மற்றும் இடைநிறுத்த சிதறல்",
    acoustic_ml_badge: "Hertzy ஒலியியல் ML",
    pitch_f0: "பிட்ச் (F0)",
    range: "வரம்பு:",
    jitter: "நடுக்கம்:",
    elevated: "அதிகரித்தது",
    stable: "நிலையானது",
    energy_level: "ஆற்றல் நிலை",
    rms_headroom: "RMS டைனமிக் ஹெட்ரூம்",
    tone_classification: "தொனி வகைப்பாடு",
    inferred_vocal_stance: "ஊகிக்கப்பட்ட குரல் நிலைப்பாடு",
    neural_formant_analysis: "நியூரல் ஃபார்மன்ட் பகுப்பாய்வு",
    prosody_rate: "ஓசை விகிதம்",
    speech_flow_cadence: "பேச்சு ஓட்டத் தாளம்",
    naturalness: "இயல்புத்தன்மை:",
    pause_duration: "இடைநிறுத்த காலம்",
    avg_intersyllabic_gap: "சராசரி அசையிடை இடைவெளி",
    unusually_rapid_synthetic: "⚠️ வழக்கத்திற்கு மாறான வேகம்/செயற்கை",
    natural_breathing_gap: "✓ இயல்பான சுவாச இடைவெளி",
    pause_frequency: "இடைநிறுத்த அதிர்வெண்",
    breathing_rate: "சுவாசம் மற்றும் தயக்க விகிதம்",
    centroid: "சென்ട്രாய்டு:",
    suspicious_vocab_title: "சந்தேகத்திற்கிடமான சொற்கள் மற்றும் அச்சுறுத்தல் சொற்றொடர்கள்",
    suspicious_vocab_subtitle: "சொற்பொருள் கட்டாயப்படுத்தல் & நிதி ஃபிஷிங் வடிகட்டி",
    detected: "கண்டறியப்பட்டது",
    all: "அனைத்தும்",
    category: "வகை:",
    no_suspicious_markers: "சந்தேகத்திற்கிடமான சொற்கள் ஏதும் கண்டறியப்படவில்லை.",
    critical: "மிக முக்கியம்",
    high: "அதிகம்",
    medium: "நடுத்தரம்",
    risk_timeline_title: "ஆபத்து மற்றும் நேர வரைபடம்",
    risk_timeline_subtitle: "கால சாளர பகுப்பாய்வு",
    all_metrics: "அனைத்து அளவீடுகள்",
    composite: "கூட்டு",
    voice_clone: "குரல் குளோன்",
    vocabulary: "சொற்களஞ்சியம்",
    tone_prosody: "தொனி / ஓசை",
    peak_voice: "உச்ச குரல் ஆபத்து:",
    peak_vocab: "உச்ச சொல் ஆபத்து:",
    windows_analyzed: "பகுப்பாய்வு செய்யப்பட்ட சாளரங்கள்:",
    slice_resolution: "துண்டு தெளிவுத்திறன்:",
    intervals: "இடைவெளிகள்",
    no_timeline_data: "காலவரிசை தரவு இல்லை. விவரக்குறிப்பை உருவாக்க ஆடியோவைப் பதிவேற்றவும்.",
    ai_summary_title: "AI நிர்வாக ஆபத்து சுருக்கம்",
    ai_summary_subtitle: "ஒருங்கிணைந்த பல மாதிரி அச்சுறுத்தல் மதிப்பீடு (4-5 புள்ளிகள் பகுப்பாய்வு)",
    awaiting_analysis_pass: "முழு ஆடியோ பகுப்பாய்வு முடியும் வரை காத்திருக்கிறது.",
    copy: "நகலெடு",
    export_json: "JSON ஏற்றுமதி",
    save_to_history: "பெட்டக வரலாற்றில் சேமி",
    saved_to_vault: "பெட்டகத்தில் சேமிக்கப்பட்டது",
    delete_audio_reset: "ஆடியோவை நீக்கு / மீட்டமை",
    vault_history_title: "ஆடியோ பகுப்பாய்வு பெட்டக வரலாறு",
    vault_history_subtitle: "சேமிக்கப்பட்ட தணிக்கை அமர்வுகள் மற்றும் ஒலி பதிவுகள்",
    search_history_placeholder: "தலைப்பு அல்லது முக்கிய சொல் மூலம் அமர்வுகளைத் தேடுங்கள்...",
    export_csv: "CSV ஏற்றுமதி",
    clear_all: "அனைத்தையும் அழி",
    load: "ஏற்று",
    delete_record: "பதிவை நீக்கு",
    no_audit_logs: "தணிக்கை பதிவுகள் எதுவும் இல்லை. பதிவுகளைப் பார்க்க அமர்வைச் சேமிக்கவும்.",
    duration_suffix: "கால அளவு",
    login_id_label: "உள்நுழைவு ஐடி / பயனர் அடையாளம்",
    login_id_placeholder: "'demo' அல்லது பயனர் ஐடியை உள்ளிடவும்",
    security_password_label: "பாதுகாப்பு கடவுச்சொல்",
    default_label: "இயல்புநிலை:",
    demo_credentials_title: "டெமோ சான்றுகள்:",
    auto_fill: "தானியங்கி நிரப்பு",
    remember_session: "இந்த சாதனத்தில் அமர்வை நினைவில் கொள்",
    auth_error_title: "அங்கீகாரப் பிழை",
    enter_credentials_error: "உள்நுழைய உங்கள் ஐடி மற்றும் கடவுச்சொல்லை உள்ளிடவும்.",
    invalid_credentials_error: "தவறான சான்றுகள். 'demo' மற்றும் 'demo123' ஐப் பயன்படுத்தவும்.",
    signing_in: "சரிபார்க்கிறது...",
    sign_in_btn: "அங்கீகரித்து பெட்டகத்தை அணுகவும்",
    security_protocol_notice: "முழுமையான குறியாக்கப் பாதுகாப்பு மற்றும் குரல் உயிரியல் பாதுகாப்புடன் பாதுகாக்கப்பட்டது.",
  },
  ml: {
    app_name: "Hertzy",
    app_tagline: "ഓരോ ശബ്ദത്തിനും ഒരു ഒപ്പുണ്ട്",
    system_live: "സിസ്റ്റം സജീവമാണ്",
    processing_audio: "ഓഡിയോ പ്രോസസ്സിംഗ് നടക്കുന്നു",
    light: "ലൈറ്റ്",
    dark: "ഡാർക്ക്",
    lang_label: "ഭാഷ:",
    history: "ചരിത്രം",
    logged_in_as: "ലോഗിൻ ചെയ്തത്:",
    sign_out: "സൈൻ ഔട്ട്",
    critical_threat: "ഗുരുതരമായ ഭീഷണി",
    elevated_threat: "ഉയർന്ന ഭീഷണി",
    moderate_risk: "മിതമായ അപകടസാധ്യത",
    low_risk: "കുറഞ്ഞ അപകടസാധ്യത",
    very_low_risk: "വളരെ കുറഞ്ഞ അപകടസാധ്യത",
    alert_high_risk_call: "സുരക്ഷാ മുന്നറിയിപ്പ്: ഉയർന്ന അപകടസാധ്യതയുള്ള വോയ്‌സ് കോൾ കണ്ടെത്തി — ഡീപ്ഫേക്ക് വോയ്‌സ് ക്ലോൺ തട്ടിപ്പിന് സാധ്യത",
    alert_safe_call: "സുരക്ഷാ അറിയിപ്പ്: പരിശോധിച്ചുറപ്പിച്ച സുരക്ഷിത കോൾ — യഥാർത്ഥ മനുഷ്യ ശബ്ദ ഒപ്പ്",
    alert_cautious_call: "സുരക്ഷാ അറിയിപ്പ്: ജാഗ്രതാ കോൾ — ശബ്ദത്തിലോ പദാവലിയിലോ അപാകതകൾ കണ്ടെത്തി",
    rerun_analysis: "വീണ്ടും വിശകലനം ചെയ്യുക",
    analysis_time: "വിശകലന സമയം",
    source: "ഉറവിടം",
    file: "ഫയൽ",
    sample: "മാതൃക",
    microphone: "മൈക്രോഫോൺ",
    upload: "അപ്‌ലോഡ്",
    temporal_window_slices: "സമയ വിൻഡോ സ്ലൈസുകൾ:",
    window_resolution: "വിൻഡോ റെസല്യൂഷൻ:",
    live_microphone: "തത്സമയ മൈക്രോഫോൺ",
    upload_audio_file: "ഓഡിയോ ഫയൽ അപ്‌ലോഡ് ചെയ്യുക",
    time_window: "സമയ വിൻഡോ:",
    mic_ready: "മൈക്രോഫോൺ തയ്യാറാണ്",
    live_audio_capture: "തത്സമയ ഓഡിയോ റെക്കോർഡിംഗ് പുരോഗമിക്കുന്നു",
    mic_ready_desc: "തത്സമയ സംഭാഷണം റെക്കോർഡ് ചെയ്യാൻ മൈക്രോഫോണിൽ ക്ലിക്ക് ചെയ്യുക. തത്സമയ വാക്കുകളും ശബ്ദ അളവുകളും താഴെ ദൃശ്യമാകും.",
    mic_recording_desc: "Hertzy റിയൽ-ടൈം ക്ലാസിഫയറിലേക്ക് ശബ്ദ സാമ്പിളുകൾ സ്ട്രീം ചെയ്യുന്നു. സ്വാഭാവികമായി സംസാരിക്കുക.",
    live_pitch: "തത്സമയ പിച്ച്",
    live_energy: "തത്സമയ ഊർജ്ജം",
    duration: "ദൈർഘ്യം",
    noise_reduction: "ശബ്ദം കുറയ്ക്കൽ",
    rms_normalization: "RMS സാധാരണവൽക്കരണം",
    on: "ഓൺ",
    off: "ഓഫ്",
    live_speech_stream: "തത്സമയ സംഭാഷണ സ്ട്രീം:",
    listening_words: "സംസാരിക്കുന്ന വാക്കുകൾക്കായി ശ്രദ്ധിക്കുന്നു...",
    drop_audio_here: "റെക്കോർഡ് ചെയ്ത ഓഡിയോ ഫയൽ ഇവിടെ ഇടുക അല്ലെങ്കിൽ",
    browse: "ബ്രൗസ് ചെയ്യുക",
    supports_formats: ".wav, .mp3, .m4a, .ogg (പരമാവധി 50MB വരെ)",
    benchmark_scenarios: "ബെഞ്ച്മാർക്ക് ഓഡിയോ സാഹചര്യങ്ങൾ (പരീക്ഷിക്കാൻ ക്ലിക്ക് ചെയ്യുക):",
    decoded_ready: "ഡീകോഡ് ചെയ്‌ത് തയ്യാറായി",
    loading_benchmark: "സാഹചര്യം ലോഡ് ചെയ്യുന്നു:",
    error_benchmark: "ശബ്ദ സിഗ്നൽ സൃഷ്ടിക്കുന്നതിൽ പിശക്.",
    live_acoustic_graph: "തത്സമയ ശബ്ദ ഗ്രാഫ്",
    streaming_active: "സ്ട്രീമിംഗ് സജീവമാണ്",
    oscilloscope_ready: "റിയൽ-ടൈം ഓസിലോസ്കോപ്പ് തയ്യാറാണ്",
    hybrid: "ഹൈബ്രിഡ്",
    oscilloscope: "ഓസിലോസ്കോപ്പ്",
    fft_spectrum: "FFT സ്പെക്ട്രം",
    signal: "സിഗ്നൽ",
    standby: "സ്റ്റാൻഡ്‌ബൈ",
    interaction_risk_gauge: "സംഭാഷണ അപകടസാധ്യത ഗേജ്",
    risk_index: "അപകടസാധ്യതാ സൂചിക",
    badge_very_low: "0-20 വളരെ കുറവ്",
    badge_low: "21-40 കുറവ്",
    badge_moderate: "41-60 മിതമായത്",
    badge_elevated: "61-80 ഉയർന്നത്",
    badge_high: "81-100 ഗുരുതരം",
    status_very_low: "വളരെ കുറഞ്ഞ അപകടസാധ്യത (സുരക്ഷിതം)",
    status_low: "കുറഞ്ഞ അപകടസാധ്യത (സാധാരണം)",
    status_moderate: "മിതമായ അപകടസാധ്യത (ജാഗ്രത)",
    status_elevated: "ഉയർന്ന ഭീഷണി (അസാധാരണം)",
    status_high: "ഗുരുതരമായ ഭീഷണി (ഡീപ്ഫേക്ക് തട്ടിപ്പ്)",
    natural_patterns: "ശബ്ദവും പദാവലിയും സ്വാഭാവികമാണ്",
    elevated_urgency: "കൂടിയ അടിയന്തിരാവസ്ഥ / ശബ്ദത്തിലെ പിരിമുറുക്കം",
    high_confidence_deepfake: "ഉയർന്ന കൃത്യതയോടെയുള്ള ഡീപ്ഫേക്ക് ആൾമാറാട്ടം",
    synthetic_probability: "Hertzy കൃത്രിമ ശബ്ദ സാധ്യത:",
    risk_weights_breakdown: "അപകടസാധ്യതാ മൂല്യനിർണ്ണയ ഭാരങ്ങൾ",
    hide: "മറയ്ക്കുക",
    vectors_count: "4 വെക്ടറുകൾ (100%)",
    vector1_title: "1. ശബ്ദ ആധികാരികതയും ഡീപ്ഫേക്ക് ടെലിമെട്രിയും",
    vector1_desc: "സ്പെക്ട്രൽ ഫേസ് സ്ലിപ്പുകൾ, ഫോർമാൻ്റ് ഹാർമോണിക്‌സ്, വോകോഡർ പിഴവുകൾ, F0 ജിറ്റർ.",
    vector2_title: "2. പദാവലി, ഫിഷിംഗ് & ഭീഷണിപ്പെടുത്തൽ വാക്കുകൾ",
    vector2_desc: "OTP ശേഖരണം, വ്യാജ ഉദ്യോഗസ്ഥ ആൾമാറാട്ടം, ബാങ്ക് ട്രാൻസ്ഫർ ആവശ്യങ്ങൾ.",
    vector3_title: "3. സ്വരം, പ്രൊസോഡി & ശബ്ദ സമ്മർദ്ദം",
    vector3_desc: "സംഭാഷണ വേഗത (WPM), ഇടവേളകളുടെ താളം, അസ്വാഭാവികമായ മോണോടോൺ.",
    vector4_title: "4. അടിയന്തിരാവസ്ഥയും ആശയവിനിമയ ഒറ്റപ്പെടുത്തലും",
    vector4_desc: "കൃത്രിമ സമയപരിധികൾ ('15 മിനിറ്റിനുള്ളിൽ'), 'എന്റെ ഫോണിലേക്ക് വിളിക്കരുത്'.",
    composite_formula: "സംയോജിത സ്കോർ സമവാക്യം:",
    weight_40: "40% ഭാരം",
    weight_25: "25% ഭാരം",
    weight_10: "10% ഭാരം",
    speech_to_text_title: "തത്സമയ സ്പീച്ച്-ടു-ടെക്സ്റ്റും വിവർത്തനവും",
    speech_to_text_subtitle: "സിൻക്രൊണൈസ്ഡ് മൾട്ടി-മോഡൽ ലിംഗ്വിസ്റ്റിക് എഞ്ചിൻ",
    side_by_side: "ഒരുമിച്ച്",
    original: "യഥാർത്ഥം",
    translation: "വിവർത്തനം",
    original_transcript_title: "യഥാർത്ഥ ഓഡിയോ ട്രാൻസ്ക്രിപ്റ്റ് (പ്രത്യേക വാക്കുകൾ സഹിതം)",
    live_translation_title: "തത്സമയ വിവർത്തനം",
    awaiting_audio: "തത്സമയ എഴുത്തുരൂപത്തിനായി ഓഡിയോ കാത്തിരിക്കുന്നു...",
    translating_realtime: "തത്സമയം വിവർത്തനം ചെയ്യുന്നു...",
    translation_will_appear: "സംഭാഷണം വിശകലനം ചെയ്യുമ്പോൾ വിവർത്തനം ഇവിടെ ദൃശ്യമാകും...",
    copy_original: "യഥാർത്ഥം പകർത്തുക",
    copy_translation: "വിവർത്തനം പകർത്തുക",
    copied: "പകർത്തി!",
    tone_telemetry_title: "സ്വരവും ശബ്ദ പ്രൊസോഡി ടെലിമെട്രിയും",
    tone_telemetry_subtitle: "F0 പിച്ച്, എനർജി RMS, താളവും ഇടവേളകളും",
    acoustic_ml_badge: "Hertzy അക്കൗസ്റ്റിക് ML",
    pitch_f0: "പിച്ച് (F0)",
    range: "പരിധി:",
    jitter: "ജിറ്റർ:",
    elevated: "ഉയർന്നത്",
    stable: "സ്ഥിരതയുള്ളത്",
    energy_level: "ഊർജ്ജ നില",
    rms_headroom: "RMS ഡൈനാമിക് ഹെഡ്‌റൂം",
    tone_classification: "സ്വഭാവ വർഗ്ഗീകരണം",
    inferred_vocal_stance: "അനുമാനിച്ച സംഭാഷണ രീതി",
    neural_formant_analysis: "ന്യൂറൽ ഫോർമാൻ്റ് വിശകലനം",
    prosody_rate: "പ്രൊസോഡി നിരക്ക്",
    speech_flow_cadence: "സംഭാഷണ ഒഴുക്കിന്റെ താളം",
    naturalness: "സ്വാഭാവികത:",
    pause_duration: "ഇടവേള ദൈർഘ്യം",
    avg_intersyllabic_gap: "ശരാശരി അക്ഷര വിടവ്",
    unusually_rapid_synthetic: "⚠️ അസാധാരണ വേഗത/കൃത്രിമം",
    natural_breathing_gap: "✓ സ്വാഭാവിക ശ്വാസോച്ഛ്വാസ ഇടവേള",
    pause_frequency: "ഇടവേള ആവൃത്തി",
    breathing_rate: "ശ്വാസോച്ഛ്വാസ നിരക്ക്",
    centroid: "സെൻട്രോയിഡ്:",
    suspicious_vocab_title: "സംശയാസ്പദമായ പദാവലിയും ഭീഷണി വാക്യങ്ങളും",
    suspicious_vocab_subtitle: "സെമാന്റിക് നിർബന്ധവും സാമ്പത്തിക ഫിഷിംഗ് ഫിൽട്ടറും",
    detected: "കണ്ടെത്തി",
    all: "എല്ലാം",
    category: "വിഭാഗം:",
    no_suspicious_markers: "സംശയാസ്പദമായ വാക്കുകൾ കണ്ടെത്തിയില്ല.",
    critical: "ഗുരുതരം",
    high: "ഉയർന്നത്",
    medium: "ഇടത്തരം",
    risk_timeline_title: "അപകടസാധ്യതയും സമയ ഗ്രാഫും",
    risk_timeline_subtitle: "സമയ വിൻഡോ വിശകലനം",
    all_metrics: "എല്ലാ മെട്രിക്‌സും",
    composite: "സംയോജിതം",
    voice_clone: "വോയ്‌സ് ക്ലോൺ",
    vocabulary: "പദാവലി",
    tone_prosody: "സ്വരം / പ്രൊസോഡി",
    peak_voice: "പരമാവധി ശബ്ദ അപകടം:",
    peak_vocab: "പരമാവധി വാക്ക് അപകടം:",
    windows_analyzed: "വിശകലനം ചെയ്ത വിൻഡോകൾ:",
    slice_resolution: "റെസല്യൂഷൻ:",
    intervals: "ഇടവേളകൾ",
    no_timeline_data: "ടൈംലൈൻ ഡാറ്റ ലഭ്യമല്ല. ഓഡിയോ അപ്‌ലോഡ് ചെയ്യുകയോ റെക്കോർഡ് ചെയ്യുകയോ ചെയ്യുക.",
    ai_summary_title: "AI എക്സിക്യൂട്ടീവ് റിസ്ക് സംഗ്രഹം",
    ai_summary_subtitle: "സംയോജിത മൾട്ടി-മോഡൽ ഭീഷണി വിലയിരുത്തൽ (4-5 പോയിന്റുകൾ)",
    awaiting_analysis_pass: "ഓഡിയോ വിശകലനം പൂർത്തിയാകാൻ കാത്തിരിക്കുന്നു.",
    copy: "പകർത്തുക",
    export_json: "JSON എക്സ്പോർട്ട്",
    save_to_history: "വോൾട്ട് ചരിത്രത്തിൽ സൂക്ഷിക്കുക",
    saved_to_vault: "വോൾട്ടിൽ സൂക്ഷിച്ചു",
    delete_audio_reset: "ഓഡിയോ ഇല്ലാതാക്കുക / റീസെറ്റ്",
    vault_history_title: "ഓഡിയോ വിശകലന വോൾട്ട് ചരിത്രം",
    vault_history_subtitle: "സൂക്ഷിച്ച ഓഡിറ്റ് സെഷനുകളും റെക്കോർഡുകളും",
    search_history_placeholder: "ശീർഷകമോ കീവേഡോ ഉപയോഗിച്ച് തിരയുക...",
    export_csv: "CSV എക്സ്പോർട്ട്",
    clear_all: "എല്ലാം മായ്ക്കുക",
    load: "ലോഡ്",
    delete_record: "റെക്കോർഡ് ഇല്ലാതാക്കുക",
    no_audit_logs: "ഓഡിറ്റ് ലോഗുകളൊന്നും കണ്ടെത്തിയില്ല. വിവരങ്ങൾ കാണാൻ സെഷൻ സൂക്ഷിക്കുക.",
    duration_suffix: "ദൈർഘ്യം",
    login_id_label: "ലോഗിൻ ഐഡി / ഉപയോക്തൃ ഐഡി",
    login_id_placeholder: "'demo' അല്ലെങ്കിൽ ഉപയോക്തൃ ഐഡി നൽകുക",
    security_password_label: "സുരക്ഷാ പാസ്‌വേഡ്",
    default_label: "ഡിഫോൾട്ട്:",
    demo_credentials_title: "ഡെമോ വിവരങ്ങൾ:",
    auto_fill: "സ്വയം പൂരിപ്പിക്കുക",
    remember_session: "ഈ ഉപകരണത്തിൽ സെഷൻ ഓർമ്മിക്കുക",
    auth_error_title: "ലോഗിൻ പിശക്",
    enter_credentials_error: "ദയവായി നിങ്ങളുടെ ഐഡിയും പാസ്‌വേഡും നൽകുക.",
    invalid_credentials_error: "തെറ്റായ വിവരങ്ങൾ. 'demo', 'demo123' ഉപയോഗിക്കുക.",
    signing_in: "പരിശോധിക്കുന്നു...",
    sign_in_btn: "പരിശോധിച്ച് വോൾട്ട് തുറക്കുക",
    security_protocol_notice: "എൻഡ്-ടു-എൻഡ് എൻക്രിപ്ഷനും വോയ്‌സ് ബയോമെട്രിക് സംരക്ഷണവുമോടെ സുരക്ഷിതമാക്കിയിരിക്കുന്നു.",
  },
  kn: {
    app_name: "Hertzy",
    app_tagline: "ಪ್ರತಿಯೊಂದು ಧ್ವನಿಗೂ ಒಂದು ಸಹಿ ಇರುತ್ತದೆ",
    system_live: "ವ್ಯವಸ್ಥೆ ಸಕ್ರಿಯವಾಗಿದೆ",
    processing_audio: "ಆಡಿಯೋ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ",
    light: "ಲೈಟ್",
    dark: "ಡಾರ್ಕ್",
    lang_label: "ಭಾಷೆ:",
    history: "ಇತಿಹಾಸ",
    logged_in_as: "ಲಾಗಿನ್ ಆಗಿರುವವರು:",
    sign_out: "ಸೈನ್ ಔಟ್",
    critical_threat: "ತೀವ್ರ ಬೆದರಿಕೆ",
    elevated_threat: "ಹೆಚ್ಚಿದ ಬೆದರಿಕೆ",
    moderate_risk: "ಮಧ್ಯಮ ಅಪಾಯ",
    low_risk: "ಕಡಿಮೆ ಅಪಾಯ",
    very_low_risk: "ಅತ್ಯಂತ ಕಡಿಮೆ ಅಪಾಯ",
    alert_high_risk_call: "ಭದ್ರತಾ ಎಚ್ಚರಿಕೆ: ಹೆಚ್ಚಿನ ಅಪಾಯದ ಧ್ವನಿ ಕರೆ ಪತ್ತೆಯಾಗಿದೆ — ಸಂಭಾವ್ಯ ಡೀಪ್‌ಫೇಕ್ ಧ್ವನಿ ಕ್ಲೋನ್ ವಂಚನೆ",
    alert_safe_call: "ಭದ್ರತಾ ಸೂಚನೆ: ಪರಿಶೀಲಿಸಲಾದ ಸುರಕ್ಷಿತ ಕರೆ — ನೈಜ ಮಾನವ ಧ್ವನಿ ಸಹಿ",
    alert_cautious_call: "ಭದ್ರತಾ ಸೂಚನೆ: ಎಚ್ಚರಿಕೆಯ ಕರೆ — ಧ್ವನಿ ಅಥವಾ ಶಬ್ದಕೋಶದಲ್ಲಿ ವೈಪರೀತ್ಯಗಳು ಪತ್ತೆಯಾಗಿವೆ",
    rerun_analysis: "ಮತ್ತೊಮ್ಮೆ ವಿಶ್ಲೇಷಿಸಿ",
    analysis_time: "ವಿಶ್ಲೇಷಣಾ ಸಮಯ",
    source: "ಮೂಲ",
    file: "ಫೈಲ್",
    sample: "ಮಾದರಿ",
    microphone: "ಮೈಕ್ರೊಫೋನ್",
    upload: "ಅಪ್‌ಲೋಡ್",
    temporal_window_slices: "ಸಮಯ ವಿಂಡೋ ಭಾಗಗಳು:",
    window_resolution: "ವಿಂಡೋ ರೆಸಲ್ಯೂಶನ್:",
    live_microphone: "ಲೈವ್ ಮೈಕ್ರೊಫೋನ್",
    upload_audio_file: "ಆಡಿಯೋ ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    time_window: "ಸಮಯ ವಿಂಡೋ:",
    mic_ready: "ಮೈಕ್ರೊಫೋನ್ ಸಿದ್ಧವಾಗಿದೆ",
    live_audio_capture: "ಲೈವ್ ಆಡಿಯೋ ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    mic_ready_desc: "ಲೈವ್ ಭಾಷಣವನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಲು ಮೈಕ್ರೊಫೋನ್ ಕ್ಲಿಕ್ ಮಾಡಿ. ನೈಜ-ಸಮಯದ ಪದಗಳು ಮತ್ತು ಧ್ವನಿ ಟೆಲಿಮೆಟ್ರಿ ಕೆಳಗೆ ಕಾಣಿಸುತ್ತದೆ.",
    mic_recording_desc: "Hertzy ರಿಯಲ್-ಟೈಮ್ ಕ್ಲಾಸಿಫೈಯರ್‌ಗೆ ಆಡಿಯೋ ಸ್ಯಾಂಪಲ್‌ಗಳನ್ನು ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ. ಸಹಜವಾಗಿ ಮಾತನಾಡಿ.",
    live_pitch: "ಲೈವ್ ಪಿಚ್",
    live_energy: "ಲೈವ್ ಎನರ್ಜಿ",
    duration: "ಅವಧಿ",
    noise_reduction: "ಶಬ್ದ ಕಡಿತ",
    rms_normalization: "RMS ಸಾಮಾನ್ಯೀಕರಣ",
    on: "ಆನ್",
    off: "ಆಫ್",
    live_speech_stream: "ಲೈವ್ ರಿಯಲ್-ಟೈಮ್ ಭಾಷಣ ಸ್ಟ್ರೀಮ್:",
    listening_words: "ಮಾತನಾಡಿದ ಪದಗಳಿಗಾಗಿ ಆಲಿಸಲಾಗುತ್ತಿದೆ...",
    drop_audio_here: "ರೆಕಾರ್ಡ್ ಮಾಡಿದ ಆಡಿಯೋ ಫೈಲ್ ಅನ್ನು ಇಲ್ಲಿ ಡ್ರಾಪ್ ಮಾಡಿ ಅಥವಾ",
    browse: "ಬ್ರೌಸ್ ಮಾಡಿ",
    supports_formats: ".wav, .mp3, .m4a, .ogg (ಗರಿಷ್ಠ 50MB ವರೆಗೆ ಬೆಂಬಲಿತ)",
    benchmark_scenarios: "ಮಾದರಿ ಧ್ವನಿ ಸನ್ನಿವೇಶಗಳು (ಪರೀಕ್ಷಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ):",
    decoded_ready: "ಡಿಕೋಡ್ ಮಾಡಲಾಗಿದೆ ಮತ್ತು ಸಿದ್ಧವಾಗಿದೆ",
    loading_benchmark: "ಮಾದರಿ ಸನ್ನಿವೇಶ ಲೋಡ್ ಆಗುತ್ತಿದೆ:",
    error_benchmark: "ಮಾದರಿ ಸಿಗ್ನಲ್ ರಚಿಸುವಲ್ಲಿ ದೋಷ.",
    live_acoustic_graph: "ಲೈವ್ ಅಕೌಸ್ಟಿಕ್ ಗ್ರಾಫ್",
    streaming_active: "ಸ್ಟ್ರೀಮಿಂಗ್ ಸಕ್ರಿಯವಾಗಿದೆ",
    oscilloscope_ready: "ರಿಯಲ್-ಟೈಮ್ ಆಸಿಲೋಸ್ಕೋಪ್ ಸಿದ್ಧವಾಗಿದೆ",
    hybrid: "ಹೈಬ್ರಿಡ್",
    oscilloscope: "ಆಸಿಲೋಸ್ಕೋಪ್",
    fft_spectrum: "FFT ಸ್ಪೆಕ್ಟ್ರಮ್",
    signal: "ಸಿಗ್ನಲ್",
    standby: "ಸ್ಟ್ಯಾಂಡ್‌ಬೈ",
    interaction_risk_gauge: "ಸಂವಾದ ಅಪಾಯ ಗೇಜ್",
    risk_index: "ಅಪಾಯ ಸೂಚ್ಯಂಕ",
    badge_very_low: "0-20 ಅತ್ಯಂತ ಕಡಿಮೆ",
    badge_low: "21-40 ಕಡಿಮೆ",
    badge_moderate: "41-60 ಮಧ್ಯಮ",
    badge_elevated: "61-80 ಹೆಚ್ಚಿದ",
    badge_high: "81-100 ಹೆಚ್ಚು",
    status_very_low: "ಅತ್ಯಂತ ಕಡಿಮೆ ಅಪಾಯ (ಸುರಕ್ಷಿತ)",
    status_low: "ಕಡಿಮೆ ಅಪಾಯ (ಸಾಮಾನ್ಯ)",
    status_moderate: "ಮಧ್ಯಮ ಅಪಾಯ (ಎಚ್ಚರಿಕೆ)",
    status_elevated: "ಹೆಚ್ಚಿದ ಬೆದರಿಕೆ (ಅಸಹಜ)",
    status_high: "ಹೆಚ್ಚಿನ ಬೆದರಿಕೆ (ಡೀಪ್‌ಫೇಕ್ ವಂಚನೆ)",
    natural_patterns: "ಧ್ವನಿ ಮತ್ತು ಶಬ್ದಕೋಶ ನಮೂನೆಗಳು ನೈಸರ್ಗಿಕವಾಗಿವೆ",
    elevated_urgency: "ಅತಿಯಾದ ಆತುರ / ಧ್ವನಿ ಒತ್ತಡ",
    high_confidence_deepfake: "ಹೆಚ್ಚಿನ ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಡೀಪ್‌ಫೇಕ್ ವಂಚನೆ",
    synthetic_probability: "Hertzy ಕೃತಕ ಧ್ವನಿ ಸಂಭವನೀಯತೆ:",
    risk_weights_breakdown: "ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ ತೂಕಗಳ ವಿವರ",
    hide: "ಮರೆಮಾಡು",
    vectors_count: "4 ವೆಕ್ಟರ್‌ಗಳು (100%)",
    vector1_title: "1. ಧ್ವನಿ ಸತ್ಯಾಸತ್ಯತೆ ಮತ್ತು ಡೀಪ್‌ಫೇಕ್ ಟೆಲಿಮೆಟ್ರಿ",
    vector1_desc: "ಸ್ಪೆಕ್ಟ್ರಲ್ ಫೇಸ್ ಸ್ಲಿಪ್ಸ್, ಹಾರ್ಮೋನಿಕ್ಸ್, ವೋಕೋಡರ್ ಕಲಾಕೃತಿಗಳು, F0 ಜಿಟ್ಟರ್.",
    vector2_title: "2. ಶಬ್ದಕೋಶ, ಫಿಶಿಂಗ್ ಮತ್ತು ಸುಲಿಗೆ ಕೀವರ್ಡ್‌ಗಳು",
    vector2_desc: "OTP ಕದಿಯುವುದು, ನಕಲಿ ಅಧಿಕಾರಿ ಸೋಗು, ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ ಬೇಡಿಕೆಗಳು.",
    vector3_title: "3. ಧ್ವನಿ ಲಯ, ಪ್ರೊಸೋಡಿ ಮತ್ತು ಧ್ವನಿ ಒತ್ತಡ",
    vector3_desc: "ಭಾಷಣದ ವೇಗ (WPM), ವಿರಾಮದ ಲಯ, ಅಸ್ವಾಭಾವಿಕ ಏಕತಾನತೆ.",
    vector4_title: "4. ಸಂದರ್ಭೋಚಿತ ತುರ್ತು ಮತ್ತು ಸಂಪರ್ಕ ಕಡಿತ",
    vector4_desc: "ಕೃತಕ ಗಡುವುಗಳು ('15 ನಿಮಿಷಗಳಲ್ಲಿ'), 'ನನ್ನ ಫೋನ್‌ಗೆ ಕರೆ ಮಾಡಬೇಡಿ'.",
    composite_formula: "ಸಂಯೋಜಿತ ಸ್ಕೋರ್ ಸೂತ್ರ:",
    weight_40: "40% ತೂಕ",
    weight_25: "25% ತೂಕ",
    weight_10: "10% ತೂಕ",
    speech_to_text_title: "ಲೈವ್ ಸ್ಪೀಚ್-ಟು-ಟೆಕ್ಸ್ಟ್ ಮತ್ತು ಅನುವಾದ",
    speech_to_text_subtitle: "ಸಿಂಕ್ರೊನೈಸ್ ಮಾಡಿದ ಬಹು-ಮಾದರಿ ಭಾಷಾ ಎಂಜಿನ್",
    side_by_side: "ಪಕ್ಕಪಕ್ಕದಲ್ಲಿ",
    original: "ಮೂಲ",
    translation: "ಅನುವಾದ",
    original_transcript_title: "ಮೂಲ ಆಡಿಯೋ ಪ್ರತಿಲೇಖನ (ಗುರುತಿಸಲಾದ ಪದಗಳೊಂದಿಗೆ)",
    live_translation_title: "ಲೈವ್ ಅನುವಾದ",
    awaiting_audio: "ಲೈವ್ ಪ್ರತಿಲೇಖನಕ್ಕಾಗಿ ಆಡಿಯೋಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ...",
    translating_realtime: "ನೈಜ ಸಮಯದಲ್ಲಿ ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ...",
    translation_will_appear: "ಮಾತು ಪ್ರಕ್ರಿಯೆಗೊಂಡಂತೆ ಅನುವಾದವು ಇಲ್ಲಿ ಗೋಚರಿಸುತ್ತದೆ...",
    copy_original: "ಮೂಲ ನಕಲಿಸಿ",
    copy_translation: "ಅನುವಾದ ನಕಲಿಸಿ",
    copied: "ನಕಲಿಸಲಾಗಿದೆ!",
    tone_telemetry_title: "ಧ್ವನಿ ಮತ್ತು ಅಕೌಸ್ಟಿಕ್ ಪ್ರೊಸೋಡಿ ಟೆಲಿಮೆಟ್ರಿ",
    tone_telemetry_subtitle: "F0 ಪಿಚ್, ಎನರ್ಜಿ RMS, ಲಯ ಮತ್ತು ವಿರಾಮಗಳ ಹರಡುವಿಕೆ",
    acoustic_ml_badge: "Hertzy ಅಕೌಸ್ಟಿಕ್ ML",
    pitch_f0: "ಪಿಚ್ (F0)",
    range: "ವ್ಯಾಪ್ತಿ:",
    jitter: "ಜಿಟ್ಟರ್:",
    elevated: "ಹೆಚ್ಚಿದ",
    stable: "ಸ್ಥಿರ",
    energy_level: "ಶಕ್ತಿ ಮಟ್ಟ",
    rms_headroom: "RMS ಡೈನಾಮಿಕ್ ಹೆಡ್‌ರೂಮ್",
    tone_classification: "ಧ್ವನಿ ವರ್ಗೀಕರಣ",
    inferred_vocal_stance: "ಅನುಮಾನಿಸಲಾದ ಧ್ವನಿ ನಿಲುವು",
    neural_formant_analysis: "ನ್ಯೂರಾಲ್ ಫಾರ್ಮೆಂಟ್ ವಿಶ್ಲೇಷಣೆ",
    prosody_rate: "ಪ್ರೊಸೋಡಿ ದರ",
    speech_flow_cadence: "ಭಾಷಣ ಹರಿವಿನ ಲಯ",
    naturalness: "ನೈಸರ್ಗಿಕತೆ:",
    pause_duration: "ವಿರಾಮದ ಅವಧಿ",
    avg_intersyllabic_gap: "ಸರಾಸರಿ ಅಕ್ಷರಗಳ ನಡುವಿನ ಅಂತರ",
    unusually_rapid_synthetic: "⚠️ ಅಸಾಮಾನ್ಯ ವೇಗ/ಕೃತಕ",
    natural_breathing_gap: "✓ ನೈಸರ್ಗಿಕ ಉಸಿರಾಟದ ಅಂತರ",
    pause_frequency: "ವಿರಾಮ ಆವರ್ತನ",
    breathing_rate: "ಉಸಿರಾಟ ಮತ್ತು ಹಿಂಜರಿಕೆ ದರ",
    centroid: "ಸೆಂಟ್ರಾಯ್ಡ್:",
    suspicious_vocab_title: "ಅನುಮಾನಾಸ್ಪದ ಶಬ್ದಕೋಶ ಮತ್ತು ಬೆದರಿಕೆ ನುಡಿಗಟ್ಟುಗಳು",
    suspicious_vocab_subtitle: "ಆರ್ಥಿಕ ಫಿಶಿಂಗ್ ಮತ್ತು ಒತ್ತಾಯದ ಫಿಲ್ಟರ್",
    detected: "ಪತ್ತೆಯಾಗಿದೆ",
    all: "ಎಲ್ಲಾ",
    category: "ವರ್ಗ:",
    no_suspicious_markers: "ಯಾವುದೇ ಅನುಮಾನಾಸ್ಪದ ಪದಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    critical: "ತೀವ್ರ",
    high: "ಹೆಚ್ಚು",
    medium: "ಮಧ್ಯಮ",
    risk_timeline_title: "ಅಪಾಯ ಮತ್ತು ಸಮಯ ಗ್ರಾಫ್",
    risk_timeline_subtitle: "ಸಮಯ ವಿಂಡೋ ವಿಶ್ಲೇಷಣೆ",
    all_metrics: "ಎಲ್ಲಾ ಮೆಟ್ರಿಕ್‌ಗಳು",
    composite: "ಸಂಯೋಜಿತ",
    voice_clone: "ಧ್ವನಿ ಕ್ಲೋನ್",
    vocabulary: "ಶಬ್ದಕೋಶ",
    tone_prosody: "ಧ್ವನಿ / ಪ್ರೊಸೋಡಿ",
    peak_voice: "ಗರಿಷ್ಠ ಧ್ವನಿ ಅಪಾಯ:",
    peak_vocab: "ಗರಿಷ್ಠ ಶಬ್ದ ಅಪಾಯ:",
    windows_analyzed: "ವಿಶ್ಲೇಷಿಸಿದ ವಿಂಡೋಗಳು:",
    slice_resolution: "ರೆಸಲ್ಯೂಶನ್:",
    intervals: "ಮಧ್ಯಂತರಗಳು",
    no_timeline_data: "ಟೈಮ್‌ಲೈನ್ ಡೇಟಾ ಇಲ್ಲ. ವಿವರಗಳನ್ನು ಪಡೆಯಲು ಆಡಿಯೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    ai_summary_title: "AI ಕಾರ್ಯನಿರ್ವಾಹಕ ಅಪಾಯದ ಸಾರಾಂಶ",
    ai_summary_subtitle: "ಸಂಯೋಜಿತ ಬಹು-ಮಾದರಿ ಬೆದರಿಕೆ ಮೌಲ್ಯಮಾಪನ (4-5 ಅಂಶಗಳು)",
    awaiting_analysis_pass: "ಆಡಿಯೋ ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಳ್ಳಲು ಕಾಯಲಾಗುತ್ತಿದೆ.",
    copy: "ನಕಲಿಸಿ",
    export_json: "JSON ರಫ್ತು",
    save_to_history: "ವಾಲ್ಟ್ ಇತಿಹಾಸದಲ್ಲಿ ಉಳಿಸಿ",
    saved_to_vault: "ವಾಲ್ಟ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ",
    delete_audio_reset: "ಆಡಿಯೋ ಅಳಿಸಿ / ಮರುಹೊಂದಿಸಿ",
    vault_history_title: "ಆಡಿಯೋ ವಿಶ್ಲೇಷಣಾ ವಾಲ್ಟ್ ಇತಿಹಾಸ",
    vault_history_subtitle: "ಉಳಿಸಲಾದ ಆಡಿಟ್ ಸೆಷನ್‌ಗಳು ಮತ್ತು ಆಡಿಯೋ ದಾಖಲೆಗಳು",
    search_history_placeholder: "ಶೀರ್ಷಿಕೆ ಅಥವಾ ಕೀವರ್ಡ್ ಮೂಲಕ ಸೆಷನ್‌ಗಳನ್ನು ಹುಡುಕಿ...",
    export_csv: "CSV ರಫ್ತು",
    clear_all: "ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ",
    load: "ಲೋಡ್",
    delete_record: "ದಾಖಲೆ ಅಳಿಸಿ",
    no_audit_logs: "ಯಾವುದೇ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ವಿವರಗಳನ್ನು ನೋಡಲು ಸೆಷನ್ ಉಳಿಸಿ.",
    duration_suffix: "ಅವಧಿ",
    login_id_label: "ಲಾಗಿನ್ ಐಡಿ / ಬಳಕೆದಾರ ಗುರುತು",
    login_id_placeholder: "'demo' ಅಥವಾ ಬಳಕೆದಾರ ಐಡಿ ನಮೂದಿಸಿ",
    security_password_label: "ಭದ್ರತಾ ಪಾಸ್‌ವರ್ಡ್",
    default_label: "ಡೀಫಾಲ್ಟ್:",
    demo_credentials_title: "ಡೆಮೊ ವಿವರಗಳು:",
    auto_fill: "ಸ್ವಯಂ ಭರ್ತಿ",
    remember_session: "ಈ ಸಾಧನದಲ್ಲಿ ಸೆಷನ್ ನೆನಪಿಡಿ",
    auth_error_title: "ದೃಢೀಕರಣ ದೋಷ",
    enter_credentials_error: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಲಾಗಿನ್ ಐಡಿ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ.",
    invalid_credentials_error: "ತಪ್ಪಾದ ವಿವರಗಳು. 'demo' ಮತ್ತು 'demo123' ಬಳಸಿ.",
    signing_in: "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    sign_in_btn: "ದೃಢೀಕರಿಸಿ ಮತ್ತು ವಾಲ್ಟ್ ಪ್ರವೇಶಿಸಿ",
    security_protocol_notice: "ಎಂಡ್-ಟು-ಎಂಡ್ ಗೂಢಲಿಪೀಕರಣ ಮತ್ತು ಧ್ವನಿ ಬಯೋಮೆಟ್ರಿಕ್ ರಕ್ಷಣೆಯೊಂದಿಗೆ ಸುರಕ್ಷಿತವಾಗಿದೆ.",
  },
};

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (code: string) => void;
  t: (key: TranslationKey, fallback?: string) => string;
  languages: LanguageOption[];
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<string>(() => {
    return localStorage.getItem("hertzy_language") || "en";
  });

  const activeLangOption = SUPPORTED_LANGUAGES.find((l) => l.code === currentLanguage) || SUPPORTED_LANGUAGES[0];
  const isRTL = activeLangOption.dir === "rtl";

  const setLanguage = (code: string) => {
    const found = SUPPORTED_LANGUAGES.find((l) => l.code === code);
    const validCode = found ? found.code : "en";
    setCurrentLanguageState(validCode);
    localStorage.setItem("hertzy_language", validCode);
  };

  useEffect(() => {
    // Synchronize HTML element direction and lang attribute
    document.documentElement.lang = currentLanguage;
    if (isRTL) {
      document.documentElement.setAttribute("dir", "rtl");
    } else {
      document.documentElement.setAttribute("dir", "ltr");
    }
  }, [currentLanguage, isRTL]);

  const EXTRA_TRANSLATIONS: Record<string, Record<string, string>> = {
    en: {
      voice_authenticity_risk: "Voice Authenticity Risk",
      neural_clone_detected: "⚠️ Neural Clone Detected",
      natural_bio_voice: "✓ Natural Biological Voice",
      flagged_threat_words: "Flagged Threat Words",
      phrases: "Phrases",
      urgency_phishing: "Urgency / Phishing",
      clean_vocabulary: "Clean Vocabulary",
      interaction_stability: "Interaction Stability",
      stability_index: "Stability Index",
      pipeline_running: "Running Hertzy Multimodal Deepfake & Risk Analysis Pipeline (Spectrogram + Vocoder Check + STT Translation)...",
      processing_frames: "Processing Frames",
    },
    hi: {
      voice_authenticity_risk: "आवाज़ प्रामाणिकता जोखिम",
      neural_clone_detected: "⚠️ न्यूरल क्लोन का पता चला",
      natural_bio_voice: "✓ स्वाभाविक जैविक आवाज़",
      flagged_threat_words: "चिह्नित संदेहास्पद शब्द",
      phrases: "वाक्यांश",
      urgency_phishing: "तात्कालिकता / फ़िशिंग",
      clean_vocabulary: "सुरक्षित शब्दावली",
      interaction_stability: "बातचीत की स्थिरता",
      stability_index: "स्थिरता सूचकांक",
      pipeline_running: "Hertzy मल्टीमॉडल डीपफ़ेक और जोखिम विश्लेषण पाइपलाइन चालू है...",
      processing_frames: "फ़्रेम प्रोसेस हो रहे हैं",
    },
    te: {
      voice_authenticity_risk: "వాయిస్ ప్రామాణికత ప్రమాదం",
      neural_clone_detected: "⚠️ న్యూరల్ క్లోన్ గుర్తించబడింది",
      natural_bio_voice: "✓ సహజ జీవసంబంధిత వాయిస్",
      flagged_threat_words: "గుర్తించిన ప్రమాదకర పదాలు",
      phrases: "పదబంధాలు",
      urgency_phishing: "అత్యవసరం / ఫిషింగ్",
      clean_vocabulary: "శుభ్రమైన పదజాలం",
      interaction_stability: "పరస్పర స్థిరత్వం",
      stability_index: "స్థిరత్వ సూచిక",
      pipeline_running: "Hertzy మల్టీమోడల్ డీప్‌ఫేక్ & రిస్క్ విశ్లేషణ పైప్‌లైన్ నడుస్తోంది...",
      processing_frames: "ఫ్రేమ్‌ల ప్రాసెసింగ్",
    },
    ar: {
      voice_authenticity_risk: "مخاطر أصالة الصوت",
      neural_clone_detected: "⚠️ تم اكتشاف استنساخ عصبي",
      natural_bio_voice: "✓ صوت بيولوجي طبيعي",
      flagged_threat_words: "الكلمات التهديدية المحددة",
      phrases: "عبارات",
      urgency_phishing: "إلحاح / تصيد احتيالي",
      clean_vocabulary: "مفردات سليمة",
      interaction_stability: "استقرار التفاعل",
      stability_index: "مؤشر الاستقرار",
      pipeline_running: "تشغيل خط أنابيب Hertzy للتحليل المتعدد الوسائط للعمق والتزييف...",
      processing_frames: "معالجة الإطارات",
    },
    bn: {
      voice_authenticity_risk: "ভয়েস সত্যতা ঝুঁকি",
      neural_clone_detected: "⚠️ নিউরাল ক্লোন শনাক্ত হয়েছে",
      natural_bio_voice: "✓ প্রাকৃতিক জৈবিক ভয়েস",
      flagged_threat_words: "চিহ্নিত হুমকি শব্দ",
      phrases: "শব্দগুচ্ছ",
      urgency_phishing: "জরুরিতা / ফিশিং",
      clean_vocabulary: "স্বচ্ছ শব্দভাণ্ডার",
      interaction_stability: "ইন্টারঅ্যাকশন স্থায়িত্ব",
      stability_index: "স্থায়িত্ব সূচক",
      pipeline_running: "Hertzy মাল্টিমোডাল ডিপফেক ও ঝুঁকি বিশ্লেষণ পাইপলাইন চলছে...",
      processing_frames: "ফ্রেম প্রসেসিং হচ্ছে",
    },
    mr: {
      voice_authenticity_risk: "आवाज सत्यता धोका",
      neural_clone_detected: "⚠️ न्यूरल क्लोन आढळले",
      natural_bio_voice: "✓ नैसर्गिक जैविक आवाज",
      flagged_threat_words: "चिन्हांकित संशयास्पद शब्द",
      phrases: "वाक्यांश",
      urgency_phishing: "तातडी / फिशिंग",
      clean_vocabulary: "सुरक्षित शब्दसंग्रह",
      interaction_stability: "संभाषण स्थिरता",
      stability_index: "स्थिरता निर्देशांक",
      pipeline_running: "Hertzy मल्टीमॉडल डीपफेक आणि जोखीम विश्लेषण सुरू आहे...",
      processing_frames: "फ्रेम प्रक्रिया सुरू आहे",
    },
    ta: {
      voice_authenticity_risk: "குரல் நம்பகத்தன்மை ஆபத்து",
      neural_clone_detected: "⚠️ நியூரல் குளோன் கண்டறியப்பட்டது",
      natural_bio_voice: "✓ இயற்கையான மனிதக் குரல்",
      flagged_threat_words: "கண்டறியப்பட்ட அச்சுறுத்தல் சொற்கள்",
      phrases: "சொற்றொடர்கள்",
      urgency_phishing: "அவசரம் / ஃபிஷிங்",
      clean_vocabulary: "பாதுகாப்பான சொற்களஞ்சியம்",
      interaction_stability: "உரையாடல் நிலைத்தன்மை",
      stability_index: "நிலைத்தன்மைக் குறியீடு",
      pipeline_running: "Hertzy மல்டிமாடல் டீப்ஃபேக் & இடர் பகுப்பாய்வு இயங்குகிறது...",
      processing_frames: "பிரேம்கள் செயலாக்கப்படுகின்றன",
    },
    ml: {
      voice_authenticity_risk: "ശബ്ദ ആധികാരികത റിസ്ക്",
      neural_clone_detected: "⚠️ ന്യൂറൽ ക്ലോൺ കണ്ടെത്തി",
      natural_bio_voice: "✓ സ്വാഭാവിക മനുഷ്യ ശബ്ദം",
      flagged_threat_words: "തിരിച്ചറിഞ്ഞ ഭീഷണി വാക്കുകൾ",
      phrases: "വാക്യങ്ങൾ",
      urgency_phishing: "അടിയന്തിരത / ഫിഷിംഗ്",
      clean_vocabulary: "സുരക്ഷിതമായ പദാവലി",
      interaction_stability: "സ്ഥിരത സൂചിക",
      stability_index: "സ്ഥിരത സൂചിക",
      pipeline_running: "Hertzy മൾട്ടിമോഡൽ ഡീപ്ഫേക്ക് & റിസ്ക് അനാലിസിസ് പൈപ്പ്‌ലൈൻ പ്രവർത്തിക്കുന്നു...",
      processing_frames: "ഫ്രെയിമുകൾ പ്രോസസ്സ് ചെയ്യുന്നു",
    },
    kn: {
      voice_authenticity_risk: "ಧ್ವನಿ ದೃಢೀಕರಣ ಅಪಾಯ",
      neural_clone_detected: "⚠️ ನ್ಯೂರಲ್ ಕ್ಲೋನ್ ಪತ್ತೆಯಾಗಿದೆ",
      natural_bio_voice: "✓ ನೈಸರ್ಗಿಕ ಜೈವಿಕ ಧ್ವನಿ",
      flagged_threat_words: "ಗುರುತಿಸಲಾದ ಬೆದರಿಕೆ ಪದಗಳು",
      phrases: "ಪದಗುಚ್ಛಗಳು",
      urgency_phishing: "ತುರ್ತು / ಫಿಶಿಂಗ್",
      clean_vocabulary: "ಸ್ಪಷ್ಟ ಶಬ್ದಕೋಶ",
      interaction_stability: "ಸಂವಹನ ಸ್ಥಿರತೆ",
      stability_index: "ಸ್ಥಿರತೆ ಸೂಚ್ಯಂಕ",
      pipeline_running: "Hertzy ಮಲ್ಟಿಮೋಡಲ್ ಡೀಪ್‌ಫೇಕ್ ಮತ್ತು ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ ಚಾಲನೆಯಲ್ಲಿದೆ...",
      processing_frames: "ಫ್ರೇಮ್‌ಗಳ ಸಂಸ್ಕರಣೆ",
    },
  };

  const t = (key: TranslationKey | string, fallback?: string): string => {
    // Check extra translations first
    const extraLang = EXTRA_TRANSLATIONS[currentLanguage] || EXTRA_TRANSLATIONS.en;
    if (extraLang && extraLang[key]) {
      return extraLang[key];
    }
    const extraEn = EXTRA_TRANSLATIONS.en[key];
    if (extraEn) {
      return extraEn;
    }

    // Check main translations dictionary
    const langDict = (TRANSLATIONS as any)[currentLanguage] || TRANSLATIONS.en;
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const englishFallback = (TRANSLATIONS.en as any)[key];
    if (englishFallback) {
      return englishFallback;
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        languages: SUPPORTED_LANGUAGES,
        isRTL,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
